"""Core route step 5: grid DFS (网格图 §1)."""

from ..questions import O, S, X

QUESTIONS = [
    dict(
        slug="max-area-of-island", n=695, title="Max Area of Island", diff="Medium", topics=["grid"],
        summary="In a grid of 0s (water) and 1s (land), return the number of cells in the largest island (4-directionally connected land), or 0.",
        example="[[1,1,0],[0,1,0],[0,0,1]]  →  3",
        criterion="Which approach is linear in the grid size?",
        hint="When you step onto unvisited land, how do you measure its whole island at once?",
        choices=[
            ("Flood fill returning the area", "DFS from each unvisited land cell, marking cells and adding up their count.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "Each island is one connected component. Marking cells as you go means every cell is counted once, by exactly one flood fill."),
            ("Flood fill per cell, no global marks", "From every land cell, explore its island from scratch.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct, but every cell of a big island re-explores the whole island."),
            ("Count all land cells", "Return the number of 1s.", "O(m·n)", "O(1)", "counting", X,
             "Two separate islands of 3 cells would give 6. Is that one island?"),
            ("Longest run in a row or column", "Find the longest straight line of 1s.", "O(m·n)", "O(1)", "matrix", X,
             "Islands bend. An L-shape of 3 cells has no straight run of 3."),
        ],
    ),
    dict(
        slug="count-islands-with-total-value-divisible-by-k", n=3619, title="Count Islands With Total Value Divisible by K", diff="Medium", topics=["grid"],
        summary="Cells hold non-negative integers; positive cells are land, 4-directionally connected into islands. Count islands whose total value is divisible by k.",
        example="[[2,3,0],[0,0,4],[1,0,6]], k = 5  →  2",
        criterion="Which approach is linear in the grid size?",
        hint="What one number does each island need to report?",
        choices=[
            ("Flood fill summing values", "DFS each unvisited island, add its values, check sum % k == 0.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "The test is on the island's total, so each island must be gathered whole. One flood fill per island visits each cell once."),
            ("Re-explore the island from every cell", "For each land cell, flood fill its island and test it, deduplicating islands.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct after deduplication, but big islands are explored once per cell."),
            ("Count cells divisible by k", "Count land cells whose own value is a multiple of k.", "O(m·n)", "O(1)", "counting", X,
             "2 and 3 aren't multiples of 5, but together they make an island worth 5."),
            ("Sum each row's land runs", "Treat each horizontal run of land as an island.", "O(m·n)", "O(1)", "matrix", X,
             "In the example, 4 and 6 are stacked vertically. Are they separate islands?"),
        ],
    ),
    dict(
        slug="maximum-number-of-fish-in-a-grid", n=2658, title="Maximum Number of Fish in a Grid", diff="Medium", topics=["grid"],
        summary="Cells are land (0) or water holding that many fish. A fisher starts on any water cell, catches every fish there and may move to adjacent water cells. Return the most fish one fisher can catch.",
        example="[[0,2,1,0],[4,0,0,3],[1,0,0,4],[0,3,2,0]]  →  7",
        criterion="Which approach is linear in the grid size?",
        hint="Once the fisher is in a connected water region, what can they reach?",
        choices=[
            ("Flood fill summing each region", "DFS each unvisited water region; keep the largest fish total.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "The fisher can sweep a whole connected water region, so the answer is the best region total. One flood fill per region."),
            ("Re-explore from every water cell", "Start a fresh search from each water cell.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct, but every cell of a region recomputes the same total."),
            ("Richest single cell", "Return the largest cell value.", "O(m·n)", "O(1)", "counting", X,
             "The fisher can keep moving to adjacent water. Why stop at one cell?"),
            ("All the fish in the grid", "Sum every water cell.", "O(m·n)", "O(1)", "counting", X,
             "Land separates regions. Can the fisher cross it?"),
        ],
    ),
    dict(
        slug="pond-sizes-lcci", n=None, ref="面试题 16.19", url="https://leetcode.cn/problems/pond-sizes-lcci/",
        title="Pond Sizes", diff="Medium", topics=["grid"],
        summary="In a terrain matrix, 0 is water. Water cells touching horizontally, vertically or diagonally form a pond. Return every pond's size in ascending order.",
        example="[[0,2,1,0],[0,1,0,1],[1,1,0,1],[0,1,0,1]]  →  [1, 2, 4]",
        criterion="Which approach is correct and linear in the grid size (plus sorting the sizes)?",
        hint="How many neighbours does a cell have here?",
        choices=[
            ("8-direction flood fill, then sort", "Fill each unvisited pond through all 8 neighbours; collect sizes and sort them.", "O(m·n + p log p)", "O(m·n)", "graph-dfs", O,
             "Diagonal contact joins ponds, so each fill must look in 8 directions. Every cell is visited once; only the p sizes get sorted."),
            ("4-direction flood fill", "Fill through up, down, left and right only.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "In the example, (0,3) and (1,2) touch only at a corner. Are they one pond?"),
            ("Re-explore from every water cell", "Start a fresh search at each 0 and deduplicate ponds.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct after deduplication, but each pond is explored once per cell."),
            ("Count zeros per row", "Treat each row's water cells as one pond.", "O(m·n)", "O(1)", "matrix", X,
             "Ponds span rows, and two zeros in one row can belong to different ponds."),
        ],
    ),
    dict(
        slug="lcs-03-theme-spaces", n=None, ref="LCS 03", url="https://leetcode.cn/problems/YesdPw/",
        title="Theme Spaces", diff="Medium", topics=["grid"],
        summary="A venue grid uses '0' for corridors and '1'–'5' for theme spaces; same-character cells connected up, down, left or right form one space. Everything outside the grid is corridor. Return the largest area of a space not adjacent to any corridor, or 0.",
        example='["110", "231", "221"]  →  1',
        criterion="Which approach is correct and linear?",
        hint="A space is disqualified by any one of its cells. Can you stop at that cell?",
        choices=[
            ("Flood fill, flag corridor contact", "Fill each same-character space fully; mark it if any cell touches '0' or the edge; keep the best unmarked area.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "The whole space must be filled even after contact is found, so its cells aren't revisited as a new space later."),
            ("Ignore the outside", "Disqualify a space only when it touches a '0' cell.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "Outside the grid is corridor too. What about spaces on the edge?"),
            ("Stop at the first corridor contact", "Abandon the fill as soon as a cell touches a corridor.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "The unvisited rest of that space is found later as if it were a separate, clean space."),
            ("Join all non-corridor cells", "Treat every non-'0' cell as part of one connected area regardless of character.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "A '2' next to a '3' belongs to a different space."),
        ],
    ),
    dict(
        slug="island-perimeter", n=463, title="Island Perimeter", diff="Easy", topics=["grid"],
        summary="A grid contains exactly one island of 1s with no lakes inside. Return the island's perimeter.",
        example="[[0,1,0,0],[1,1,1,0],[0,1,0,0],[1,1,0,0]]  →  16",
        criterion="Which approach is linear with O(1) extra space?",
        hint="Each land cell has 4 edges. When does an edge stop counting?",
        choices=[
            ("Count cells and shared edges", "perimeter = 4·land − 2·(land pairs sharing an edge), checking right and down neighbours.", "O(m·n)", "O(1)", "counting", O,
             "Every shared edge hides one side of each of its two cells. A single scan counts both quantities without any traversal."),
            ("DFS counting edges to water", "Flood fill the island; add one for each neighbour that is water or off-grid.", "O(m·n)", "O(m·n)", "graph-dfs", S,
             "Correct, but the recursion and visited marks cost O(m·n) space. Do you need connectivity at all when there is only one island?"),
            ("4 × number of land cells", "Each cell contributes 4.", "O(m·n)", "O(1)", "counting", X,
             "Two adjacent cells share an edge that isn't on the outside."),
            ("Bounding-box perimeter", "Return 2·(width + height) of the island's bounding box.", "O(m·n)", "O(1)", "matrix", X,
             "A plus shape has the same bounding box as a full square but more edge. Does the box see the notches?"),
        ],
    ),
    dict(
        slug="flood-fill", n=733, title="Flood Fill", diff="Easy", topics=["grid"],
        summary="Recolor the starting pixel and every pixel 4-directionally connected to it with the same original color. Return the image.",
        example="[[1,1,1],[1,1,0],[1,0,1]], start (1,1), color 2  →  [[2,2,2],[2,2,0],[2,0,1]]",
        criterion="Which approach is correct and linear?",
        hint="What happens if the new color equals the old one?",
        choices=[
            ("DFS recolor; exit if colors are equal", "If the original equals the new color return; else recolor matching neighbours recursively.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "Recoloring marks a pixel as visited. The early exit matters because when the colors are equal, recolored pixels still match."),
            ("DFS recolor without the check", "Recolor and recurse into neighbours with the original color.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "With new color = old color, every recolored pixel still looks unvisited. When does the search stop?"),
            ("Recolor every original-colored pixel", "Scan the image and change all pixels of that color.", "O(m·n)", "O(1)", "matrix", X,
             "Pixels of the same color elsewhere aren't connected to the start. Should they change?"),
            ("Sweep until nothing changes", "Repeatedly recolor pixels next to recolored ones.", "O((m·n)²)", "O(1)", "brute", S,
             "Correct, but each sweep may only grow the region by one step. A search grows it all at once."),
        ],
    ),
    dict(
        slug="coloring-a-border", n=1034, title="Coloring A Border", diff="Medium", topics=["grid"],
        summary="Take the 4-directionally connected component of grid[row][col] (same color). Its border is the cells adjacent to a cell outside the component or on the grid edge. Color the border and return the grid.",
        example="[[1,1],[1,2]], row 0, col 0, color 3  →  [[3,3],[3,2]]",
        criterion="Which approach is correct and linear?",
        hint="If you recolor a cell while still exploring, what will its neighbours think?",
        choices=[
            ("DFS with visited, recolor afterwards", "Explore the component, collect border cells, then recolor them all at the end.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "The border test compares against the original colors, so it must finish before anything changes. Collect first, paint second."),
            ("Recolor during the DFS", "Paint border cells as soon as you find them.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "An interior cell next to a freshly painted cell now sees a different color and looks like border too."),
            ("Color the whole component", "Paint every cell of the component.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "Only the border should change. What about the interior cells?"),
            ("Color component cells on the grid edge", "Paint only cells in the outermost rows and columns.", "O(m·n)", "O(m·n)", "matrix", X,
             "Cells next to a different color are border too, even in the middle of the grid."),
        ],
    ),
    dict(
        slug="number-of-enclaves", n=1020, title="Number of Enclaves", diff="Medium", topics=["grid"],
        summary="Count land cells from which you cannot walk off the grid by moving 4-directionally through land.",
        example="[[0,0,0,0],[1,0,1,0],[0,1,1,0],[0,0,0,0]]  →  3",
        criterion="Which approach is linear in the grid size?",
        hint="Instead of asking whether each cell can escape, which cells can you prove escape?",
        choices=[
            ("Flood fill from border land", "Sink all land connected to the edge; count the land that remains.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "A cell escapes exactly when it's connected to edge land. Starting from the edge marks all of them in one sweep."),
            ("Search from every land cell", "For each land cell, DFS to see whether it reaches the edge.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct, but cells of the same island repeat the same search."),
            ("Land not on the edge", "Count land cells outside the outer ring.", "O(m·n)", "O(1)", "matrix", X,
             "An interior cell connected to edge land can still walk off."),
            ("Islands that don't touch the edge", "Count enclosed islands.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "The question counts cells, not islands."),
        ],
    ),
    dict(
        slug="maximum-number-of-moves-in-a-grid", n=2684, title="Maximum Number of Moves in a Grid", diff="Medium", topics=["grid", "dp"],
        summary="Start at any cell in the first column. From (r, c) you may move to (r−1, c+1), (r, c+1) or (r+1, c+1) if that cell's value is strictly larger. Return the most moves possible.",
        example="[[2,4,3,5],[5,4,9,3],[3,4,2,11],[10,9,13,15]]  →  3",
        criterion="Which approach is linear in the grid size with O(m) extra space?",
        hint="Moves always go one column right. What do you need to know about column c to fill in column c + 1?",
        choices=[
            ("Sweep columns of reachable cells", "Track which cells of the current column are reachable; derive the next column; stop when none are.", "O(m·n)", "O(m)", "dp-1d", O,
             "Every move advances one column, so reachability spreads column by column. The last column with a reachable cell is the answer."),
            ("DFS with memo", "Longest path from each cell, cached in an m×n table.", "O(m·n)", "O(m·n)", "graph-dfs", S,
             "Correct and linear, but the cache and recursion use O(m·n) space."),
            ("DFS from every start, no memo", "Try every path from each first-column cell.", "O(m·3ⁿ)", "O(n)", "brute", S,
             "Correct, but paths branch three ways per step. Many reach the same cell repeatedly."),
            ("Greedy: smallest larger neighbour", "Always step to the smallest strictly larger option.", "O(m + n)", "O(1)", "greedy", X,
             "A small step now can lead into a dead end that a bigger step avoids."),
        ],
    ),
    dict(
        slug="number-of-closed-islands", n=1254, title="Number of Closed Islands", diff="Medium", topics=["grid"],
        summary="Here 0 is land and 1 is water. A closed island is a group of land cells completely surrounded by water, so it never touches the grid edge. Count closed islands.",
        example="[[1,1,1,1,1,1,1,0],[1,0,0,0,0,1,1,0],[1,0,1,0,1,1,1,0],[1,0,0,0,0,1,0,1],[1,1,1,1,1,1,1,0]]  →  2",
        criterion="Which approach is correct and linear?",
        hint="If a search stops the moment it touches the edge, what happens to the rest of that island?",
        choices=[
            ("Sink edge islands, then count", "Flood fill land touching the edge first; every remaining island is closed.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "Removing edge-connected land leaves only closed islands, which a normal island count then finds — each cell visited a constant number of times."),
            ("DFS that stops at the edge", "Return false as soon as the search reaches the edge.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "Stopping early leaves part of that island unmarked. Later it's found again and may be miscounted as a closed island."),
            ("Check only the starting cell", "Count islands whose first-found cell isn't on the edge.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "An island can start inside and still reach the edge further along."),
            ("Re-explore per land cell", "For each land cell, BFS its whole island and test whether it touches the edge.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct after deduplication, but large islands are explored many times."),
        ],
    ),
    dict(
        slug="surrounded-regions", n=130, title="Surrounded Regions", diff="Medium", topics=["grid"],
        summary="Capture every region of 'O' cells that is completely surrounded by 'X' by flipping it to 'X'. Regions connected to the edge stay.",
        example='[["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]  →  only the edge O at (3,1) remains',
        criterion="Which approach is linear in the grid size?",
        hint="Which 'O' cells are definitely safe?",
        choices=[
            ("Mark edge-connected O's, flip the rest", "Flood fill from every edge 'O'; then flip unmarked 'O' to 'X'.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "A region survives exactly when it touches the edge. Marking from the edge finds every survivor in one sweep."),
            ("Search from every O", "For each 'O', DFS to see if it reaches the edge.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct, but cells of one region repeat the same search."),
            ("Flip every interior O", "Change all 'O' not on the outer ring.", "O(m·n)", "O(1)", "matrix", X,
             "An interior 'O' connected to an edge 'O' isn't surrounded."),
            ("Flip O's with X on all four sides", "Change an 'O' if its four neighbours are 'X'.", "O(m·n)", "O(1)", "matrix", X,
             "A surrounded region of two 'O's has an 'O' neighbour each. Would either flip?"),
        ],
    ),
    dict(
        slug="count-sub-islands", n=1905, title="Count Sub Islands", diff="Medium", topics=["grid"],
        summary="Given two grids of the same size, count the islands in grid2 whose every cell is also land in grid1.",
        example="grid1 = [[1,1],[0,1]], grid2 = [[1,0],[0,1]]  →  2",
        criterion="Which approach is correct and linear?",
        hint="To mark an island as visited, how much of it must the search cover?",
        choices=[
            ("Flood fill each grid2 island fully", "Visit every cell of the island; it's a sub-island if no cell is water in grid1.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "The search keeps going after a bad cell so the whole island is marked, and records whether any cell failed."),
            ("Stop at the first bad cell", "Return false as soon as a cell is water in grid1.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "The unvisited rest of that island gets found again later — and may be counted as its own sub-island."),
            ("Overlaps grid1 land", "Count grid2 islands with at least one cell on grid1 land.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "Overlap isn't containment. Every cell must be land in grid1."),
            ("Islands of grid1 AND grid2", "Count islands in the cellwise AND of the two grids.", "O(m·n)", "O(m·n)", "matrix", X,
             "The AND can cut one grid2 island into pieces and count each. Is a cut-up island a sub-island?"),
        ],
    ),
    dict(
        slug="minesweeper", n=529, title="Minesweeper", diff="Medium", topics=["grid"],
        summary="Apply one click to a Minesweeper board: a mine becomes 'X'; an empty cell shows its count of adjacent mines (8 directions), or, if that is 0, becomes 'B' and reveals its neighbours recursively.",
        example="click (3, 0) on a 4×5 board with one mine at (1, 2)  →  everything revealed except the cells boxed in by the 1s",
        criterion="Which approach reveals exactly the right cells with the least work?",
        hint="Which revealed cells keep the cascade going?",
        choices=[
            ("DFS that expands only from blanks", "Count adjacent mines; if 0 mark 'B' and recurse into unrevealed neighbours, else write the digit.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "Only zero-count cells open their neighbours, which is the game's rule. Each cell is counted and revealed at most once."),
            ("Also expand from numbered cells", "Recurse into the neighbours of every revealed cell.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "A numbered cell borders a mine. If it opened its neighbours, what might get revealed?"),
            ("Reveal every non-mine cell", "Replace all 'E' with digits or 'B'.", "O(m·n)", "O(1)", "matrix", X,
             "Cells walled off by numbered cells stay hidden after a click."),
            ("Precompute all mine counts first", "Count adjacent mines for every cell, then run the cascade.", "O(m·n)", "O(m·n)", "matrix", S,
             "Correct, but it counts mines around cells the click never reaches."),
        ],
    ),
    dict(
        slug="pacific-atlantic-water-flow", n=417, title="Pacific Atlantic Water Flow", diff="Medium", topics=["grid"],
        summary="Rain flows from a cell to a neighbour of equal or lower height. The Pacific touches the top and left edges, the Atlantic the bottom and right. Return every cell from which water can reach both oceans.",
        example="[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]  →  [[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]",
        criterion="Which approach is linear in the grid size?",
        hint="Rather than following water down from every cell, where could you start and walk uphill?",
        choices=[
            ("Reverse flood fill from each ocean", "From each ocean's edge, DFS uphill (to ≥ heights); return cells reached from both.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "Reversing the flow turns 'which oceans can I reach' into two searches from the coasts. Each cell is visited at most twice."),
            ("Downhill search from every cell", "For each cell, DFS downhill and note which oceans it reaches.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct, but every search may cover the whole grid."),
            ("Cells touching both coasts", "Return the top-right and bottom-left corner regions.", "O(m + n)", "O(1)", "matrix", X,
             "Water can travel across the grid. In the example, (2,2) sits in the middle."),
            ("Walk uphill to strictly higher only", "Reverse flood fill, but only into strictly higher cells.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "Water also flows across equal heights. What happens on a flat stretch?"),
        ],
    ),
    dict(
        slug="lcp-63-marble-game", n=None, ref="LCP 63", url="https://leetcode.cn/problems/EXvqDp/",
        title="Marble Game", diff="Medium", topics=["grid"],
        summary="A board has holes 'O', counter-clockwise turners 'W', clockwise turners 'E' and empty cells. A marble may be shot in from any empty non-corner edge cell, perpendicular to that edge, and moves at most num steps. Return every start from which it falls into a hole.",
        example='num = 4, plate = ["..E.", ".EOW", "..W."]  →  [[2, 1]]',
        criterion="Which approach is fastest when num can be 10⁶?",
        hint="Movement is deterministic and every turner can be undone. Can two different shots ever share a (cell, direction) state?",
        choices=[
            ("Simulate each shot, capped at num", "From every valid edge start, follow the marble until a hole, the edge or num steps.", "O(N·M)", "O(1)", "matrix", O,
             "Each state has exactly one predecessor, so paths from different starts never merge or loop. Together they cover each (cell, direction) at most once — O(N·M) in total, whatever num is."),
            ("Memo table of outcomes", "Cache, for every cell and direction, where the marble ends and after how many steps.", "O(N·M)", "O(N·M)", "dp-2d", S,
             "Correct, but the cache only helps if paths share states — and they never do. It costs O(N·M) memory for nothing."),
            ("Shortest path to a hole", "BFS from each start toward the nearest hole.", "O(N·M) per start", "O(N·M)", "graph-bfs", X,
             "The marble doesn't choose its route; it goes where the turners send it."),
            ("Ignore the step limit", "Simulate until the marble stops, regardless of num.", "O(N·M)", "O(1)", "matrix", X,
             "A marble that reaches a hole after more than num steps doesn't count."),
        ],
    ),
    dict(
        slug="number-of-islands-ii", n=305, title="Number of Islands II", diff="Hard", topics=["grid", "data-structures"],
        summary="An m×n grid starts as all water. Positions are turned into land one at a time (possibly repeating). After each addition, report the number of islands.",
        example="m = 3, n = 3, positions = [[0,0],[0,1],[1,2],[2,1]]  →  [1, 1, 2, 3]",
        criterion="Which approach handles k additions fastest?",
        hint="A new cell can only merge islands. How do you know whether two neighbours already share one?",
        choices=[
            ("Union-find", "Skip repeats; count +1, then union with land neighbours, −1 per successful union.", "O(k·α(m·n))", "O(m·n)", "union-find", O,
             "Union-find answers 'same island?' in near-constant time, and each successful union merges two islands into one."),
            ("Recount with flood fill each time", "After each addition, count islands from scratch.", "O(k·m·n)", "O(m·n)", "graph-dfs", S,
             "Correct, but each step rescans the whole grid for one changed cell."),
            ("+1 minus land neighbours", "Add 1, subtract the number of adjacent land cells.", "O(k)", "O(m·n)", "counting", X,
             "Two neighbours may already be on the same island. Subtracting both merges it twice."),
            ("Treat every position as new", "Union-find, but process repeated positions again.", "O(k·α(m·n))", "O(m·n)", "union-find", X,
             "Re-adding an existing land cell counts +1 for an island that doesn't exist."),
        ],
    ),
    dict(
        slug="number-of-spaces-cleaning-robot-cleaned", n=2061, title="Number of Spaces Cleaning Robot Cleaned", diff="Medium", topics=["grid"],
        summary="A robot starts at the top-left of a room (0 = empty, 1 = object) facing right. It moves straight, cleaning cells, and turns 90° clockwise whenever the next cell is blocked or outside. It runs forever. Count the cells it cleans.",
        example="[[0,0,0],[1,1,0],[0,0,0]]  →  7",
        criterion="Which approach stops exactly when nothing new can happen?",
        hint="When is the robot guaranteed to repeat itself forever?",
        choices=[
            ("Simulate until a (cell, direction) repeats", "Track visited states; stop at the first repeated state.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "Movement depends only on position and heading. Once a state repeats, the robot loops forever, so nothing new can be cleaned."),
            ("Stop when a cell repeats", "End the simulation at the first revisited cell.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "Passing a cell again in a different direction can lead somewhere new."),
            ("Simulate 4·m·n steps", "Run a fixed number of steps, counting distinct cells.", "O(m·n)", "O(m·n)", "brute", S,
             "Correct, since there are only 4·m·n states, but it keeps going long after the path has started repeating."),
            ("Count reachable empty cells", "Flood fill from the start and count.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "The robot only goes straight and turns right at obstacles. Can it steer into every reachable cell?"),
        ],
    ),
    dict(
        slug="sum-of-remoteness-of-all-cells", n=2852, title="Sum of Remoteness of All Cells", diff="Medium", topics=["grid"],
        summary="Cells are blocked (−1) or hold a positive value. A cell's remoteness is the sum of values of the open cells it cannot reach. Return the total remoteness over all open cells.",
        example="[[−1,1,−1],[5,−1,4],[−1,3,−1]]  →  39",
        criterion="Which approach is linear in the grid size?",
        hint="Do two cells in the same region have the same remoteness?",
        choices=[
            ("Per region: (total − region sum) × size", "Flood fill each region for its sum s and size c; add (T − s)·c.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "A cell can't reach exactly the cells outside its region, so every cell in a region shares one remoteness. One fill per region suffices."),
            ("Search from every cell", "For each open cell, explore its region and sum the rest.", "O((m·n)²)", "O(m·n)", "brute", S,
             "Correct, but cells in the same region repeat the same search."),
            ("Total minus each cell's own value", "Add (T − value) for every open cell.", "O(m·n)", "O(1)", "math", X,
             "A cell reaches its whole region, not only itself."),
            ("Count unreachable cells", "Add the number of cells each cell can't reach.", "O(m·n)", "O(m·n)", "counting", X,
             "Remoteness adds values, not cells."),
        ],
    ),
    dict(
        slug="robot-room-cleaner", n=489, title="Robot Room Cleaner", diff="Hard", topics=["grid", "trees"],
        summary="Control a robot in an unknown room through move(), turnLeft(), turnRight() and clean(). You don't know the layout or your position. Clean every reachable cell.",
        example="An unseen room with obstacles; the robot starts somewhere open  →  every reachable cell cleaned",
        criterion="Which approach is guaranteed to clean every reachable cell?",
        hint="After exploring in one direction, how does the robot get back to where it was?",
        choices=[
            ("Backtracking DFS with relative coordinates", "Track visited (x, y) from the start; try 4 directions; after each move, turn around, move back and restore the heading.", "O(N)", "O(N)", "backtrack", O,
             "Relative coordinates replace the unknown map. Physically retracing each step restores the robot's state, so the DFS can continue from the previous cell."),
            ("DFS without stepping back", "Recurse into new cells but never return the robot.", "O(N)", "O(N)", "graph-dfs", X,
             "When the recursion returns, the robot is still somewhere else. Which cell does the next try start from?"),
            ("Spiral outward", "Move in a growing spiral until blocked.", "O(N)", "O(1)", "matrix", X,
             "Obstacles break the spiral, and rooms behind them never get visited."),
            ("Random walk until idle", "Move randomly; stop after a long stretch with no new cells.", "O(?)", "O(N)", "brute", X,
             "However long you wait, can you be sure no cell is left?"),
        ],
    ),
]
