"""Core route step 4: binary tree DFS (链表、树与回溯 §2.2 top-down, §2.3 bottom-up)."""

from ..questions import O, S, X

QUESTIONS = [
    # ---------------------------------------------------------------- §2.2 top-down DFS
    dict(
        slug="minimum-depth-of-binary-tree", n=111, title="Minimum Depth of Binary Tree", diff="Easy", topics=["trees"],
        summary="Return the number of nodes on the shortest path from the root down to a leaf (a node with no children).",
        example="[3, 9, 20, null, null, 15, 7]  →  2",
        criterion="Which approach can stop as soon as the answer is known, even on a very lopsided tree?",
        hint="Which traversal meets the shallowest leaf first?",
        choices=[
            ("BFS, stop at the first leaf", "Process the tree level by level; return the depth of the first leaf dequeued.", "O(n)", "O(w)", "tree-bfs", O,
             "Level order finishes depth d before touching depth d+1, so the first leaf you meet is the shallowest. Nothing deeper is ever visited."),
            ("DFS: 1 + min(children)", "depth(node) = 1 + min(depth(left), depth(right)), with depth(null) = 0.", "O(n)", "O(h)", "tree-dfs", X,
             "A node with only a right child isn't a leaf, yet min(0, right) picks the missing side. Which nodes are allowed to end a path?"),
            ("DFS that skips missing children", "Recurse; when one child is null, use only the other child's depth.", "O(n)", "O(h)", "tree-dfs", S,
             "Correct, but it always explores the whole tree. If a leaf sits at depth 2 beside a path 10⁴ deep, why walk the long path?"),
            ("Follow the leftmost path", "Walk left children from the root until null and count.", "O(h)", "O(1)", "tree-dfs", X,
             "Is the left spine always shortest? It may also stop at a node that still has a right child — not a leaf at all."),
        ],
    ),
    dict(
        slug="path-sum", n=112, title="Path Sum", diff="Easy", topics=["trees"],
        summary="Decide whether some root-to-leaf path has node values that add up to targetSum. Values may be negative.",
        example="[5,4,8,11,null,13,4,7,2,null,null,null,1], targetSum = 22  →  true",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What should a child be asked to find, given what its parent has already used up?",
        choices=[
            ("DFS passing the remaining sum", "Subtract each value on the way down; at a leaf, check the remainder is 0.", "O(n)", "O(h)", "tree-dfs", O,
             "The remainder carries everything the path above you contributed. Each node is visited once, and only the current path is on the stack."),
            ("Collect every root-to-leaf path", "Store each path as a list, then sum each list.", "O(n·h)", "O(n·h)", "array-copy", S,
             "Correct, but copying paths costs up to n·h. A running number already says everything a stored path would."),
            ("Prune once the sum overshoots", "Stop exploring a branch when the running sum exceeds targetSum.", "O(n)", "O(h)", "tree-dfs", X,
             "Values can be negative. Can a path that overshoots come back down to the target?"),
            ("Accept a match at any node", "Return true as soon as the remaining sum reaches 0, leaf or not.", "O(n)", "O(h)", "tree-dfs", X,
             "The path must end at a leaf. In [1, 2] with target 1, the root alone matches — but is it a leaf?"),
        ],
    ),
    dict(
        slug="sum-root-to-leaf-numbers", n=129, title="Sum Root to Leaf Numbers", diff="Medium", topics=["trees"],
        summary="Each node holds a digit 0–9. Every root-to-leaf path spells a number. Return the sum of all those numbers.",
        example="[1, 2, 3]  →  12 + 13 = 25",
        criterion="Which approach is linear without building strings?",
        hint="Going one level down, how does the number spelled so far change?",
        choices=[
            ("DFS carrying cur·10 + digit", "Pass the number so far down; at a leaf, add it to the total.", "O(n)", "O(h)", "tree-dfs", O,
             "Appending a digit is cur·10 + d. Carry that down and each leaf already holds its whole number."),
            ("Build path strings, parse at leaves", "Append digits to a string and convert it at each leaf.", "O(n·h)", "O(h)", "array-copy", S,
             "Correct, but every leaf parses a string of length h. Integer arithmetic does the same in O(1) per step."),
            ("Add digit × 10^depth per node", "Weight each node's digit by its distance from the root.", "O(n)", "O(h)", "math", X,
             "A node shared by two paths belongs to both numbers, and its place value depends on how far below it each leaf is. Does one term per node capture that?"),
            ("Return each subtree's list of numbers", "Each subtree returns (value, length) pairs; the parent prefixes its digit.", "O(n·L)", "O(n)", "recursion", S,
             "Correct, but every list is rebuilt at every ancestor. Top-down, the prefix is known before you reach the leaf."),
        ],
    ),
    dict(
        slug="binary-tree-right-side-view", n=199, title="Binary Tree Right Side View", diff="Medium", topics=["trees"],
        summary="Return the values you would see looking at a binary tree from the right: the last node on each level, top to bottom.",
        example="[1, 2, 3, null, 5, null, 4]  →  [1, 3, 4]",
        criterion="Which approach is linear with O(h) extra space?",
        hint="If you always visit the right child first, which node is the first to reach each new depth?",
        choices=[
            ("DFS, right child first", "Record a node when its depth equals the answer's length.", "O(n)", "O(h)", "tree-dfs", O,
             "Going right first, the first node you meet at each depth is the rightmost one. Only the recursion stack is needed."),
            ("BFS, last node per level", "Process level by level and keep each level's last node.", "O(n)", "O(w)", "tree-bfs", S,
             "Correct and common, but the queue holds a whole level — up to n/2 nodes in a full tree. Does that meet the space limit?"),
            ("Follow right children from the root", "Walk the right spine and collect its values.", "O(h)", "O(1)", "tree-dfs", X,
             "In [1, 2, 3, 4], node 4 hangs under the left child, yet it's the only node on its level. Is the right spine always what you see?"),
            ("BFS, first node per level", "Process level by level and keep each level's first node.", "O(n)", "O(w)", "tree-bfs", X,
             "The first node of each level is what you'd see from the left. Which end of the level faces right?"),
        ],
    ),
    dict(
        slug="count-good-nodes-in-binary-tree", n=1448, title="Count Good Nodes in Binary Tree", diff="Medium", topics=["trees"],
        summary="A node is good if no node on the path from the root to it has a greater value. Count the good nodes.",
        example="[3, 1, 4, 3, null, 1, 5]  →  4",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What single number summarizes everything a node needs to know about the path above it?",
        choices=[
            ("DFS passing the path maximum", "A node is good if its value ≥ the max so far; pass max(max, value) down.", "O(n)", "O(h)", "tree-dfs", O,
             "Only the largest ancestor can disqualify a node, so the running max is the whole story. One visit per node."),
            ("Re-scan ancestors per node", "Keep parent pointers and walk up from every node to the root.", "O(n·h)", "O(n)", "brute", S,
             "Correct, but every node repeats the walk its parent already did. What could the parent hand down instead?"),
            ("Compare with the parent only", "Count nodes whose value ≥ their parent's.", "O(n)", "O(h)", "tree-dfs", X,
             "In 3 → 1 → 2, node 2 beats its parent but not the root. Is it good?"),
            ("Compare with the root only", "Count nodes whose value ≥ the root's.", "O(n)", "O(h)", "tree-dfs", X,
             "In 3 → 5 → 4, node 4 ≥ 3 but sits below 5. Which ancestor actually matters?"),
        ],
    ),
    dict(
        slug="sum-of-nodes-with-even-valued-grandparent", n=1315, title="Sum of Nodes with Even-Valued Grandparent", diff="Medium", topics=["trees"],
        summary="Return the sum of values of all nodes whose grandparent exists and has an even value.",
        example="[6,7,8,2,7,1,3,9,null,1,4,null,null,null,5]  →  18",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What does a node need to know about the two levels directly above it?",
        choices=[
            ("DFS passing parent and grandparent", "Carry (parent, grandparent) values down; shift them one level per step.", "O(n)", "O(h)", "tree-dfs", O,
             "A node only needs its grandparent's parity. Passing two values down gives it that without any lookup structure."),
            ("Parent map, then look up grandparents", "Record every node's parent, then check each node's grandparent.", "O(n)", "O(n)", "hashmap", S,
             "Correct, but the map stores every node. The recursion already knows the ancestors as it descends."),
            ("Sum nodes with an even parent", "Add a node when its parent's value is even.", "O(n)", "O(h)", "tree-dfs", X,
             "That's one level too close. Whose parity does the problem ask about?"),
            ("Sum even nodes at depth ≥ 2", "Add every even-valued node that has a grandparent.", "O(n)", "O(h)", "tree-dfs", X,
             "The condition is on the grandparent's value, not the node's own value."),
        ],
    ),
    dict(
        slug="smallest-string-starting-from-leaf", n=988, title="Smallest String Starting From Leaf", diff="Medium", topics=["trees"],
        summary="Each node holds a letter (0 = 'a' … 25 = 'z'). Among strings read from a leaf up to the root, return the lexicographically smallest.",
        example="[0, 1, 2, 3, 4, 3, 4]  →  \"dba\"",
        criterion="Which approach always returns the right string?",
        hint="Is the smaller of two child strings still smaller once the parent's letter is appended to both?",
        choices=[
            ("DFS with the path; compare at leaves", "Keep the root-to-node path; at each leaf, reverse it and keep the minimum.", "O(n·h)", "O(h)", "tree-dfs", O,
             "The string starts at the leaf, so it's only fully known once you reach one. Comparing complete strings at the leaves avoids every shortcut's trap."),
            ("Bottom-up: min(child strings) + letter", "Each node returns the smaller child string with its own letter appended.", "O(n·h)", "O(n·h)", "recursion", X,
             "'a' < 'ab', but after appending 'z': is 'az' < 'abz'? Appending can flip which string is smaller."),
            ("Greedy: step to the smaller child letter", "From the root, always go to the child with the smaller letter.", "O(h)", "O(1)", "greedy", X,
             "The string is read from the leaf, so the root end matters least — and what do you do when both children have the same letter?"),
            ("Generate all leaf strings and sort", "Build every leaf-to-root string, sort, take the first.", "O(L·h log L)", "O(L·h)", "sort", S,
             "Correct, but you only need the minimum. Why sort them all?"),
        ],
    ),
    dict(
        slug="maximum-difference-between-node-and-ancestor", n=1026, title="Maximum Difference Between Node and Ancestor", diff="Medium", topics=["trees"],
        summary="Return the largest |a.val − b.val| where node a is an ancestor of node b.",
        example="[8,3,10,1,6,null,14,null,null,4,7,13]  →  7",
        criterion="Which approach is linear with O(h) extra space?",
        hint="For a given node, which two ancestor values could produce the largest difference?",
        choices=[
            ("DFS passing the path min and max", "Carry the smallest and largest value on the path; compare at each node.", "O(n)", "O(h)", "tree-dfs", O,
             "The best ancestor for a node is either the smallest or the largest one above it. Two numbers passed down cover every ancestor."),
            ("Compare each node with every ancestor", "Keep the path in a list and scan it at every node.", "O(n·h)", "O(h)", "brute", S,
             "Correct, but each scan repeats work. Do you need every ancestor, or only the extremes?"),
            ("Compare with the parent only", "Take the largest |node − parent|.", "O(n)", "O(h)", "tree-dfs", X,
             "In 8 → 3 → 1, the best pair is 8 and 1, two levels apart. Can parent–child pairs find it?"),
            ("Global max minus global min", "Find the largest and smallest values in the whole tree.", "O(n)", "O(h)", "math", X,
             "The max and min can sit in different branches, where neither is an ancestor of the other."),
        ],
    ),
    dict(
        slug="sum-of-root-to-leaf-binary-numbers", n=1022, title="Sum of Root To Leaf Binary Numbers", diff="Easy", topics=["trees"],
        summary="Each node is 0 or 1. Every root-to-leaf path is a binary number with the root as the most significant bit. Return the sum.",
        example="[1, 0, 1, 0, 1, 0, 1]  →  22",
        criterion="Which approach is linear with O(h) extra space?",
        hint="Appending a bit to a binary number does what to its value?",
        choices=[
            ("DFS carrying cur·2 + bit", "Pass (cur << 1) | bit down; add cur at each leaf.", "O(n)", "O(h)", "tree-dfs", O,
             "Shifting left and adding the bit is how a binary number grows by one digit. Each leaf ends up holding its full value."),
            ("Build bit strings, parse at leaves", "Append '0'/'1' along the path and parse base 2 at each leaf.", "O(n·h)", "O(h)", "array-copy", S,
             "Correct, but each leaf re-reads a string of length h. A running integer does the same in O(1) per step."),
            ("Weight bits by tree height", "Add bit × 2^(height − depth) for every node.", "O(n)", "O(h)", "math", X,
             "That only works if every leaf is on the bottom level — and a shared node belongs to several paths, so one term isn't enough."),
            ("Bottom-up: add own bit to child sums", "Each subtree returns its sum; the parent adds its bit once.", "O(n)", "O(h)", "recursion", X,
             "A parent's bit belongs to every path below it, at a different place value in each. Does adding it once account for that?"),
        ],
    ),
    dict(
        slug="add-one-row-to-tree", n=623, title="Add One Row to Tree", diff="Medium", topics=["trees"],
        summary="Insert a row of nodes with value val at a given depth. Each node at depth − 1 gets two new children, and its old left and right subtrees move under the new left and right nodes. If depth is 1, the new node becomes the root.",
        example="root = [4,2,6,3,1,5], val = 1, depth = 2  →  [4,1,1,2,null,null,6,3,1,5]",
        criterion="Which approach is correct and touches only the nodes it must?",
        hint="Which nodes actually change their children?",
        choices=[
            ("DFS to depth − 1 and splice", "Stop at depth − 1; insert new nodes between each node and its children. Handle depth 1 separately.", "O(n)", "O(h)", "tree-dfs", O,
             "Only nodes at depth − 1 change. Splicing there moves whole subtrees by relinking — nothing below is visited."),
            ("Rebuild the whole tree", "Copy the tree recursively, inserting new nodes at the target depth.", "O(n)", "O(n)", "array-copy", S,
             "Correct, but the subtrees below just move. Why copy nodes you could relink?"),
            ("Attach new nodes under depth-level nodes", "Give every node at depth new leaf children.", "O(n)", "O(h)", "tree-dfs", X,
             "That adds the row one level too deep, under the old nodes. The old subtrees must hang beneath the new row."),
            ("Splice at depth − 1, no special case", "Always insert under nodes at depth − 1.", "O(n)", "O(h)", "tree-dfs", X,
             "When depth is 1, which node sits at depth 0? The new node has to become the root."),
        ],
    ),
    dict(
        slug="extract-kth-character-from-the-rope-tree", n=2689, title="Extract Kth Character From The Rope Tree", diff="Easy", topics=["trees"],
        summary="In a rope tree, leaves hold non-empty strings and each internal node stores the length of the string formed by its left subtree followed by its right subtree. Return the k-th character (1-indexed) of the root's string.",
        example='internal(len 5) → leaves "ab", "cde", k = 3  →  "c"',
        criterion="Which approach makes the best use of the stored lengths?",
        hint="Knowing the left part's length, can you tell which side holds position k?",
        choices=[
            ("Descend by comparing k with the left length", "If k ≤ left length go left, else subtract it and go right.", "O(h)", "O(1)", "binary-search", O,
             "The lengths tell you which half holds position k, like indexing into a split range. One path from root to leaf is enough."),
            ("Build the full string", "Concatenate the leaves in order, then index into it.", "O(n + |S|)", "O(|S|)", "array-copy", S,
             "Correct, but it materializes the whole string. Why build what you only need one character of?"),
            ("In-order walk counting characters", "Visit leaves left to right until k characters have passed.", "O(n + |S|)", "O(h)", "tree-dfs", S,
             "Correct, but it reads everything before position k. The stored lengths let you skip whole subtrees."),
            ("Pick leaf number ⌈k / leaves⌉", "Divide k by the number of leaves to choose a leaf.", "O(n)", "O(h)", "math", X,
             "Leaves hold strings of different lengths. Why would positions split evenly across them?"),
        ],
    ),
    dict(
        slug="binary-tree-longest-consecutive-sequence", n=298, title="Binary Tree Longest Consecutive Sequence", diff="Medium", topics=["trees"],
        summary="Return the length of the longest downward path (parent to child) along which each value is exactly one more than the previous.",
        example="[1, null, 3, 2, 4, null, null, null, 5]  →  3  (3 → 4 → 5)",
        criterion="Which approach is linear with O(h) extra space?",
        hint="When a child is exactly parent + 1, what happens to the current run? And otherwise?",
        choices=[
            ("DFS passing the current run length", "If child = parent + 1, extend the run; else restart at 1. Track the max.", "O(n)", "O(h)", "tree-dfs", O,
             "A run can only continue from its parent, so the parent's run length is all a child needs. One visit per node."),
            ("Search downward from every node", "From each node, follow +1 children as far as possible.", "O(n²)", "O(h)", "brute", S,
             "Correct, but a node inside a long run is re-walked from every node above it. Can the run be carried instead?"),
            ("Sort all values, longest run", "Collect the values, sort them and find the longest consecutive run.", "O(n log n)", "O(n)", "sort", X,
             "Consecutive values anywhere in the tree don't make a parent-to-child path."),
            ("Only runs starting at the root", "Follow +1 children from the root.", "O(h)", "O(h)", "tree-dfs", X,
             "In the example the best run 3 → 4 → 5 starts below the root. Where can a run begin?"),
        ],
    ),
    dict(
        slug="check-if-a-string-is-a-valid-sequence-from-root-to-leaves-path-in-a-binary-tree", n=1430,
        title="Valid Sequence from Root to Leaf", diff="Medium", topics=["trees"],
        summary="Given an array arr, decide whether it equals the values along some root-to-leaf path of a binary tree.",
        example="root = [0,1,0,0,1,0,null,null,1,0,0], arr = [0,1,0,1]  →  true",
        criterion="Which approach explores only what can still match?",
        hint="At depth i, which nodes are still worth exploring?",
        choices=[
            ("DFS with an index, prune mismatches", "Go deeper only while node.val = arr[i]; succeed at a leaf when i is the last index.", "O(n)", "O(h)", "tree-dfs", O,
             "A mismatch kills the whole subtree, so most branches are cut early. The leaf check at the last index enforces 'root to leaf'."),
            ("Enumerate every root-to-leaf path", "Store all paths and compare each with arr.", "O(n·h)", "O(n·h)", "array-copy", S,
             "Correct, but it builds paths that already failed at their first value. Why not stop there?"),
            ("Match without the leaf check", "Return true once all of arr has matched along a path.", "O(n)", "O(h)", "tree-dfs", X,
             "arr may match a path that keeps going past its last element. Must the path end exactly there?"),
            ("Check arr[i] appears at depth i", "For each i, look for any node with value arr[i] at depth i.", "O(n)", "O(w)", "tree-bfs", X,
             "The right values at the right depths can sit on different branches. Do they form one path?"),
        ],
    ),
    dict(
        slug="boundary-of-binary-tree", n=545, title="Boundary of Binary Tree", diff="Medium", topics=["trees"],
        summary="Return the boundary counter-clockwise from the root: the root, the left boundary (no leaves), all leaves left to right, then the right boundary (no leaves) bottom-up.",
        example="[1, null, 2, 3, 4]  →  [1, 3, 4, 2]",
        criterion="Which approach is linear and emits each node exactly once?",
        hint="Split the boundary into parts with clear start and stop rules.",
        choices=[
            ("Left edge, leaves, reversed right edge", "Walk the left boundary from root.left (prefer left, else right) skipping leaves; DFS for leaves; collect the right boundary and reverse it.", "O(n)", "O(h)", "tree-dfs", O,
             "Each part has a precise rule, and skipping leaves on the edges means no node is emitted twice."),
            ("First and last node of each level", "Level order; take each level's ends, then the whole last level.", "O(n)", "O(w)", "tree-bfs", X,
             "A leaf on a middle level is on the boundary but may be neither first nor last on its level. Where would it come from?"),
            ("Left view + leaves + right view", "Combine the left and right side views with the leaves.", "O(n)", "O(h)", "tree-dfs", X,
             "The left view can pick a node from the root's right subtree when the left side is shallow. Is that node on the left boundary?"),
            ("Collect all three, then dedupe", "Gather the edges and leaves loosely and remove repeats with a set.", "O(n)", "O(n)", "set", S,
             "It works, but the set patches over overlap that exact start and stop rules avoid — and it costs O(n) extra space."),
        ],
    ),
    # ---------------------------------------------------------------- §2.3 bottom-up DFS
    dict(
        slug="univalued-binary-tree", n=965, title="Univalued Binary Tree", diff="Easy", topics=["trees"],
        summary="Decide whether every node in a binary tree has the same value.",
        example="[1, 1, 1, 1, 1, null, 1]  →  true",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What one value must every node match?",
        choices=[
            ("DFS comparing with the root value", "Return false at the first node that differs.", "O(n)", "O(h)", "tree-dfs", O,
             "Every node must equal the root, so one comparison per node, stopping at the first mismatch."),
            ("Collect values into a set", "Insert every value; check the set has size 1.", "O(n)", "O(n)", "set", S,
             "Correct, but the set grows with the tree and never stops early."),
            ("Check the root's children only", "Compare root.left and root.right with the root.", "O(1)", "O(1)", "tree-dfs", X,
             "What about the grandchildren and everything below?"),
            ("Sum equals count × root", "Compare the value sum with node count × root value.", "O(n)", "O(h)", "math", X,
             "Different values can balance out: root 2 with children 1 and 3 sums to 6 = 3 × 2."),
        ],
    ),
    dict(
        slug="same-tree", n=100, title="Same Tree", diff="Easy", topics=["trees"],
        summary="Decide whether two binary trees have the same shape and the same values in the same places.",
        example="[1, 2, 3] and [1, 2, 3]  →  true",
        criterion="Which approach is linear with O(h) extra space?",
        hint="If the roots match, what must be true of their subtrees?",
        choices=[
            ("Walk both trees together", "Compare roots, then recurse on (left, left) and (right, right).", "O(n)", "O(h)", "tree-dfs", O,
             "Two trees are equal exactly when roots match and both pairs of subtrees are equal. One lockstep walk checks that."),
            ("Compare in-order traversals", "Check that the in-order value lists are equal.", "O(n)", "O(n)", "array-copy", X,
             "Root 1 with left child 2, and root 2 with right child 1, both read [2, 1] in order. Same tree?"),
            ("Serialize with null markers", "Write both trees as strings including nulls and compare.", "O(n)", "O(n)", "array-copy", S,
             "Correct, because nulls pin down the shape, but it builds two full strings. Comparing in place needs no copies."),
            ("Compare sizes and value sums", "Equal if the node counts and sums match.", "O(n)", "O(h)", "math", X,
             "[1, 2] and [1, null, 2] have the same count and sum. Same shape?"),
        ],
    ),
    dict(
        slug="symmetric-tree", n=101, title="Symmetric Tree", diff="Easy", topics=["trees"],
        summary="Decide whether a binary tree is a mirror image of itself around its center.",
        example="[1, 2, 2, 3, 4, 4, 3]  →  true",
        criterion="Which approach is linear with O(h) extra space?",
        hint="When comparing two mirrored subtrees, which child of one pairs with which child of the other?",
        choices=[
            ("Mirror DFS on two pointers", "Compare (a.left, b.right) and (a.right, b.left) recursively.", "O(n)", "O(h)", "tree-dfs", O,
             "A mirror pairs the outside children together and the inside children together. Walking both halves that way checks it in one pass."),
            ("Each level is a palindrome", "Level order with null placeholders; check each level reads the same backwards.", "O(n)", "O(w)", "tree-bfs", S,
             "Correct if you keep the nulls, but it holds a whole level at once."),
            ("Left subtree equals right subtree", "Run a same-tree check on root.left and root.right.", "O(n)", "O(h)", "tree-dfs", X,
             "Equal isn't mirrored. In [1, 2, 2, 3, 4, 3, 4], the halves are equal — but is the tree symmetric?"),
            ("In-order is a palindrome", "Check the in-order value list reads the same backwards.", "O(n)", "O(n)", "array-copy", X,
             "[1, 2, 2, null, 2, null, 2] reads 2, 2, 1, 2, 2 in order, yet both 2s lean right. Mirror?"),
        ],
    ),
    dict(
        slug="flip-equivalent-binary-trees", n=951, title="Flip Equivalent Binary Trees", diff="Medium", topics=["trees"],
        summary="A flip swaps a node's left and right children. Decide whether two trees with unique values can be made equal by flipping any set of nodes.",
        example="[1,2,3,4,5,6,null,null,null,7,8] and [1,3,2,null,6,4,5,null,null,null,null,8,7]  →  true",
        criterion="Which approach is linear?",
        hint="If the roots match, how many ways can their children pair up?",
        choices=[
            ("Recurse: children straight or crossed", "Roots must match; then (l1~l2 and r1~r2) or (l1~r2 and r1~l2).", "O(n)", "O(h)", "tree-dfs", O,
             "With unique values, at most one pairing has matching child roots, so the other fails at once. Each node pair is examined a constant number of times."),
            ("Try every combination of flips", "Enumerate subsets of nodes to flip and compare.", "O(2ⁿ·n)", "O(n)", "brute", S,
             "Correct, but exponential. A flip at one node never affects whether its subtrees can match."),
            ("Compare sorted value lists", "Equal if both trees contain the same values.", "O(n log n)", "O(n)", "sort", X,
             "Flips keep each node's parent. Do equal value sets guarantee equal parents?"),
            ("Same values on each level", "Compare each level's values as a set.", "O(n)", "O(w)", "tree-bfs", X,
             "A node can sit on the right level under a different parent — no flip can move it there."),
        ],
    ),
    dict(
        slug="find-a-corresponding-node-of-a-binary-tree-in-a-clone-of-that-tree", n=1379,
        title="Find a Corresponding Node in a Clone", diff="Easy", topics=["trees"],
        summary="You are given a binary tree, an exact copy of it, and a reference to a node in the original. Return the reference to the same node in the copy.",
        example="target = the node with value 3 in the original  →  the node with value 3 in the copy",
        criterion="Which approach still works when values repeat?",
        hint="How can you know where you are in the copy while walking the original?",
        choices=[
            ("Walk both trees in lockstep", "DFS both at once; when the original node is target (by reference), return the copy's node.", "O(n)", "O(h)", "tree-dfs", O,
             "The copy has the same shape, so moving identically in both keeps you on corresponding nodes. Comparing references, not values, handles duplicates."),
            ("Search the copy by value", "Find a node in the copy whose value equals target's.", "O(n)", "O(h)", "tree-dfs", X,
             "With repeated values, which of the equal nodes did they mean?"),
            ("Parent map, then replay the path", "Map parents in the original, rebuild target's root path, replay it on the copy.", "O(n)", "O(n)", "hashmap", S,
             "Correct, but the map stores every node. Walking both trees together tracks the path for free."),
            ("Return target itself", "Hand back the reference you were given.", "O(1)", "O(1)", "brute", X,
             "That node lives in the original tree. Which tree must the answer belong to?"),
        ],
    ),
    dict(
        slug="balanced-binary-tree", n=110, title="Balanced Binary Tree", diff="Easy", topics=["trees"],
        summary="Decide whether a binary tree is height-balanced: at every node, the left and right subtree heights differ by at most one.",
        example="[3, 9, 20, null, null, 15, 7]  →  true",
        criterion="Which approach is linear?",
        hint="Could one recursive call return both a height and a verdict?",
        choices=[
            ("Bottom-up: height or −1", "Return each subtree's height, or −1 as soon as any subtree is unbalanced.", "O(n)", "O(h)", "tree-dfs", O,
             "Children report their heights once, and the parent checks the difference on the spot. A −1 short-circuits everything above it."),
            ("Top-down: heights at every node", "At each node compute both heights from scratch, then recurse.", "O(n²)", "O(h)", "recursion", S,
             "Correct, but each subtree's height is recomputed for every ancestor — quadratic on a skewed tree."),
            ("Check the root only", "Compare the root's left and right heights.", "O(n)", "O(h)", "tree-dfs", X,
             "Both root subtrees can have equal height while one of them is badly lopsided inside."),
            ("Max depth − min depth ≤ 1", "Compare the deepest and shallowest leaf.", "O(n)", "O(h)", "tree-dfs", X,
             "Balanced trees can have leaves at depths 2 and 4. The rule is per node, not per leaf."),
        ],
    ),
    dict(
        slug="invert-binary-tree", n=226, title="Invert Binary Tree", diff="Easy", topics=["trees"],
        summary="Mirror a binary tree by swapping the left and right children of every node. Return the root.",
        example="[4, 2, 7, 1, 3, 6, 9]  →  [4, 7, 2, 9, 6, 3, 1]",
        criterion="Which approach is linear with O(h) extra space?",
        hint="Is a mirrored tree just every node with its children swapped?",
        choices=[
            ("Recursive swap at every node", "Swap left and right, then invert both subtrees.", "O(n)", "O(h)", "tree-dfs", O,
             "Mirroring is exactly a swap at every node. Recursion visits each once with only the current path on the stack."),
            ("BFS swapping with a queue", "Pop a node, swap its children, push them.", "O(n)", "O(w)", "tree-bfs", S,
             "Correct, but the queue can hold a whole level — up to n/2 nodes."),
            ("Swap the root's children only", "Exchange root.left and root.right.", "O(1)", "O(1)", "tree-dfs", X,
             "The subtrees move, but are they mirrored inside?"),
            ("Reverse each level's values", "Collect each level and write its values back reversed.", "O(n)", "O(w)", "tree-bfs", X,
             "Values move but the shape doesn't. In [1, 2, null, 3], where should the empty spots end up?"),
        ],
    ),
    dict(
        slug="merge-two-binary-trees", n=617, title="Merge Two Binary Trees", diff="Easy", topics=["trees"],
        summary="Overlay two binary trees: where both have a node, sum the values; where only one does, use that node.",
        example="[1, 3, 2, 5] + [2, 1, 3, null, 4, null, 7]  →  [3, 4, 5, 5, 4, null, 7]",
        criterion="Which approach does the least work?",
        hint="When one side is missing, what can you return without looking further?",
        choices=[
            ("DFS, reuse a subtree when the other is null", "If one node is null return the other; else sum and recurse.", "O(min(n₁, n₂))", "O(min(h₁, h₂))", "tree-dfs", O,
             "Where one tree has nothing, the other's whole subtree is already the answer. Only overlapping nodes are visited."),
            ("Copy both trees into a new one", "Build a fresh tree visiting every node of both inputs.", "O(n₁ + n₂)", "O(n₁ + n₂)", "array-copy", S,
             "Correct and leaves inputs untouched, but it visits every node, not just the overlap."),
            ("Heap-indexed arrays, add elementwise", "Place nodes at 2i+1 / 2i+2, add the arrays, rebuild.", "O(2^h)", "O(2^h)", "array-copy", S,
             "Correct, but a skinny tree of depth 30 needs 2³⁰ slots. Pointers don't pay for empty space."),
            ("Add in-order lists, rebuild", "Sum the in-order traversals and rebuild a tree.", "O(n)", "O(n)", "array-copy", X,
             "An in-order list alone can't pin down a tree's shape. Which tree would you rebuild?"),
        ],
    ),
    dict(
        slug="evaluate-boolean-binary-tree", n=2331, title="Evaluate Boolean Binary Tree", diff="Easy", topics=["trees"],
        summary="Leaves are 0 (False) or 1 (True). Internal nodes are 2 (OR) or 3 (AND) and have two children. Return the value of the root.",
        example="[2, 1, 3, null, null, 0, 1]  →  true",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What does an operator node need before it can produce its value?",
        choices=[
            ("Post-order evaluation", "Evaluate both children, then apply OR or AND.", "O(n)", "O(h)", "tree-dfs", O,
             "An operator needs its operands first — post-order gives exactly that, once per node."),
            ("Read leaves left to right as an expression", "Join the leaves with their parents' operators and evaluate left to right.", "O(n)", "O(n)", "array-copy", X,
             "Grouping comes from the tree's shape. Does a flat left-to-right reading keep it?"),
            ("Majority of true leaves", "Return true if more leaves are 1 than 0.", "O(n)", "O(h)", "counting", X,
             "One AND over a false leaf makes its whole subtree false, however many trues it has."),
            ("Collapse bottom operators repeatedly", "Scan for operators with two leaf children, replace them, repeat.", "O(n·h)", "O(h)", "brute", S,
             "Correct, but each pass rescans the tree. A single post-order does every collapse in order."),
        ],
    ),
    dict(
        slug="most-frequent-subtree-sum", n=508, title="Most Frequent Subtree Sum", diff="Medium", topics=["trees"],
        summary="A subtree sum is the sum of all values in a node's subtree. Return every subtree sum that occurs most often.",
        example="[5, 2, −3]  →  [2, −3, 4]",
        criterion="Which approach is linear?",
        hint="Can each node's subtree sum be built from its children's?",
        choices=[
            ("Post-order sums + hash map counts", "Return each subtree sum upward and count it in a map.", "O(n)", "O(n)", "hashmap", O,
             "sum(node) = val + sum(left) + sum(right), so post-order gets every sum in one pass. A map counts them as they appear."),
            ("Recompute each subtree's sum", "For every node, traverse its subtree to sum it.", "O(n²)", "O(n)", "brute", S,
             "Correct, but nodes deep down are summed again for every ancestor. Children already know their sums."),
            ("Post-order, then sort the sums", "Collect all sums, sort, count runs.", "O(n log n)", "O(n)", "sort", S,
             "Correct, but sorting is only there to group equal sums. A hash map groups them in O(1) each."),
            ("Count node values instead", "Return the most frequent node value.", "O(n)", "O(n)", "hashmap", X,
             "A subtree sum includes all descendants. Is a node's own value its subtree sum?"),
        ],
    ),
    dict(
        slug="binary-tree-tilt", n=563, title="Binary Tree Tilt", diff="Easy", topics=["trees"],
        summary="A node's tilt is |sum of its left subtree − sum of its right subtree|. Return the sum of every node's tilt.",
        example="[4, 2, 9, 3, 5, null, 7]  →  15",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What should each recursive call return so its parent can compute its own tilt?",
        choices=[
            ("Post-order returning subtree sums", "Return the subtree sum; add |left − right| to a running total.", "O(n)", "O(h)", "tree-dfs", O,
             "Tilt needs both children's subtree sums, which is exactly what post-order hands back. One pass computes all tilts."),
            ("Recompute sums at every node", "For each node, sum its left and right subtrees from scratch.", "O(n²)", "O(h)", "brute", S,
             "Correct, but deep subtrees are summed once per ancestor."),
            ("Tilt of the root only", "Return |sum(left) − sum(right)| at the root.", "O(n)", "O(h)", "tree-dfs", X,
             "The answer adds every node's tilt, not just the root's."),
            ("Use the children's values", "Add |left.val − right.val| at each node.", "O(n)", "O(h)", "tree-dfs", X,
             "Tilt compares whole subtree sums. Does a child's own value stand for its entire subtree?"),
        ],
    ),
    dict(
        slug="count-dominant-nodes-in-a-binary-tree", n=3997, url="https://leetcode.cn/problems/count-dominant-nodes-in-a-binary-tree/",
        title="Count Dominant Nodes in a Binary Tree", diff="Medium", topics=["trees"],
        summary="In a complete binary tree, a node is dominant if its value equals the maximum value in its subtree (itself and all descendants). Count the dominant nodes.",
        example="[5, 3, 8, 2, 4, 7, 1]  →  5",
        criterion="Which approach is linear?",
        hint="What single number should each subtree report to its parent?",
        choices=[
            ("Post-order returning the subtree max", "Each call returns max(val, left max, right max); count nodes with val ≥ both children's maxima.", "O(n)", "O(log n)", "tree-dfs", O,
             "A node is dominant exactly when nothing below it is larger, and the children's maxima say that in O(1). The tree is complete, so the stack is only log n deep."),
            ("Recompute each subtree's max", "For every node, scan its whole subtree.", "O(n log n)", "O(log n)", "brute", S,
             "Correct, but each node is rescanned once per ancestor — log n times in a complete tree."),
            ("Compare with the children's values", "Dominant if val ≥ both children's values.", "O(n)", "O(log n)", "tree-dfs", X,
             "A grandchild can be larger than both children. Do the children's own values rule it out?"),
            ("Strictly greater than everything below", "Dominant only if val beats every descendant.", "O(n)", "O(log n)", "tree-dfs", X,
             "Equal counts as the maximum. In [1, 2, 3, 1, 2], the 2 above another 2 is dominant."),
        ],
    ),
    dict(
        slug="construct-string-from-binary-tree", n=606, title="Construct String from Binary Tree", diff="Medium", topics=["trees"],
        summary="Write a binary tree as a pre-order string: each child in parentheses after its parent. Drop empty parentheses unless a node has a right child but no left one.",
        example="[1, 2, 3, null, 4]  →  \"1(2()(4))(3)\"",
        criterion="Which approach is correct and linear in the output size?",
        hint="When does an empty pair of parentheses carry information?",
        choices=[
            ("Pre-order into one buffer", "Append val; add (left) if left or right exists; add (right) if right exists.", "O(n)", "O(h)", "tree-dfs", O,
             "One shared buffer means each character is written once. The '()' is kept only when it marks a missing left child before a right one."),
            ("Return and concatenate strings", "Each call returns its subtree's string; the parent joins them.", "O(n·h)", "O(n·h)", "recursion", S,
             "Correct, but each level copies its children's strings again — quadratic on a skewed tree."),
            ("Always write both children", "Emit '()' for every missing child.", "O(n)", "O(h)", "tree-dfs", X,
             "The rules drop empty pairs that aren't needed. Does a leaf need '()()'?"),
            ("Drop every empty pair", "Never emit '()'.", "O(n)", "O(h)", "tree-dfs", X,
             "Then 1(2(4)) could mean 4 is a left or a right child. How would a reader tell?"),
        ],
    ),
    dict(
        slug="count-nodes-equal-to-average-of-subtree", n=2265, title="Count Nodes Equal to Average of Subtree", diff="Medium", topics=["trees"],
        summary="Count nodes whose value equals the average of the values in their subtree, rounded down.",
        example="[4, 8, 5, 0, 1, null, 6]  →  5",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What two numbers about a subtree let you compute its average?",
        choices=[
            ("Post-order returning (sum, count)", "Combine the children's sums and counts; compare val with sum // count.", "O(n)", "O(h)", "tree-dfs", O,
             "A subtree's sum and size come straight from its children's, so one pass gets every average."),
            ("Recompute each subtree", "For every node, traverse its subtree to sum and count.", "O(n²)", "O(h)", "brute", S,
             "Correct, but deep nodes are re-summed once per ancestor."),
            ("Average of the children only", "Compare val with the average of its children's values.", "O(n)", "O(h)", "tree-dfs", X,
             "The average is over the whole subtree, including the node itself and every descendant."),
            ("Compare with the exact average", "Use sum / count without rounding.", "O(n)", "O(h)", "tree-dfs", X,
             "The average rounds down here. Node 2 over children 2 and 3 averages 7/3 → 2 — does an exact comparison count it?"),
        ],
    ),
    dict(
        slug="k-th-largest-perfect-subtree-size-in-binary-tree", n=3319, title="K-th Largest Perfect Subtree Size in Binary Tree", diff="Medium", topics=["trees"],
        summary="A perfect binary tree has every internal node with two children and all leaves on one level. Return the size of the k-th largest perfect subtree, or −1 if there are fewer than k.",
        example="root = [5,3,6,5,2,5,7,1,8,null,null,6,8], k = 2  →  3",
        criterion="Which approach finds every perfect subtree in one pass?",
        hint="If both children are perfect, what else must hold for the parent to be perfect?",
        choices=[
            ("Post-order height, then sort sizes", "Return a perfect subtree's height (−1 if not); size is 2^(h+1) − 1; sort the sizes.", "O(n log n)", "O(n)", "tree-dfs", O,
             "A node is perfect exactly when both children are perfect with the same height. Children report that in O(1), so one pass finds them all."),
            ("Check perfectness from every node", "For each node, walk its subtree to test it.", "O(n²)", "O(n)", "brute", S,
             "Correct, but every subtree is re-walked for each ancestor."),
            ("Two children everywhere", "Call a subtree perfect if every internal node has two children.", "O(n)", "O(h)", "tree-dfs", X,
             "Full isn't perfect: both children can exist with leaves at different depths."),
            ("Size of the form 2ᵏ − 1", "Treat any subtree with 1, 3, 7, … nodes as perfect.", "O(n)", "O(h)", "math", X,
             "A chain of three nodes has size 3. Is it perfect?"),
        ],
    ),
    dict(
        slug="maximum-product-of-splitted-binary-tree", n=1339, title="Maximum Product of Splitted Binary Tree", diff="Medium", topics=["trees"],
        summary="Remove one edge to split the tree in two. Maximize the product of the two parts' sums; return it modulo 10⁹ + 7.",
        example="[1, 2, 3, 4, 5, 6]  →  110",
        criterion="Which approach is linear and returns the true maximum?",
        hint="Cutting the edge above a node splits off exactly its subtree. What are the two sums?",
        choices=[
            ("Total, then post-order subtree sums", "First get the total T; then maximize s · (T − s) over subtree sums s.", "O(n)", "O(h)", "tree-dfs", O,
             "Every cut separates one subtree with sum s from the rest, T − s. Post-order gives every s once; take the modulo only at the end."),
            ("Recompute both sides per edge", "For each edge, sum both resulting trees.", "O(n²)", "O(h)", "brute", S,
             "Correct, but each cut rescans the tree. All subtree sums come from one pass."),
            ("Compare products after the modulo", "Keep max(s · (T − s) mod 10⁹+7).", "O(n)", "O(h)", "math", X,
             "A larger product can wrap around to a smaller remainder. When should the modulo be applied?"),
            ("Cut only at the root", "Try the root's two edges.", "O(n)", "O(h)", "tree-dfs", X,
             "The most even split may be deep inside a subtree."),
        ],
    ),
    dict(
        slug="finish-time-of-tasks-i", n=3965, url="https://leetcode.cn/problems/finish-time-of-tasks-i/",
        title="Finish Time of Tasks I", diff="Medium", topics=["trees"],
        summary="Tasks form a tree rooted at 0 (edges [parent, child]), each with a base time. A leaf finishes at its base time. Otherwise, with earliest and latest the children's finish times, the task takes (latest − earliest) + base and finishes at latest plus that. Return task 0's finish time.",
        example="edges = [[0,1],[0,2]], baseTime = [4,7,6]  →  12",
        criterion="Which approach is linear?",
        hint="What does a task need from its children before it can compute its own finish time?",
        choices=[
            ("Post-order over child lists", "Build child lists; compute children first, then finish = 2·latest − earliest + base.", "O(n)", "O(n)", "tree-dfs", O,
             "A task depends only on its children's finish times, so post-order computes each task once. An explicit stack avoids recursion limits on a 10⁵-deep chain."),
            ("Repeated sweeps", "Scan all tasks repeatedly, finishing any whose children are all done.", "O(n·h)", "O(n)", "brute", S,
             "Correct, but each sweep may finish only one more level. Post-order gets the order right in one pass."),
            ("Latest child plus base", "finish = latest + base.", "O(n)", "O(n)", "tree-dfs", X,
             "The task's own duration also grows by latest − earliest. Where did that term go?"),
            ("Sum of children's finish times", "finish = sum of children's finish times + base.", "O(n)", "O(n)", "math", X,
             "Children run side by side; only the earliest and latest matter. In the example, 7 + 6 + 4 = 17, not 12."),
        ],
    ),
    dict(
        slug="subtree-of-another-tree", n=572, title="Subtree of Another Tree", diff="Easy", topics=["trees", "strings"],
        summary="Decide whether subRoot is identical to the subtree rooted at some node of root (that node and all its descendants).",
        example="root = [3, 4, 5, 1, 2], subRoot = [4, 1, 2]  →  true",
        criterion="Which approach is linear in the size of both trees?",
        hint="If both trees were strings that keep their shape, what kind of search is this?",
        choices=[
            ("Serialize with null markers, then KMP", "Pre-order both with nulls and delimiters; search with KMP.", "O(m + n)", "O(m + n)", "array-copy", O,
             "Null markers and delimiters make the strings encode shape exactly, so a match is a subtree. KMP finds it in linear time."),
            ("Same-tree check at every node", "For each node of root, compare its subtree with subRoot.", "O(m·n)", "O(h)", "tree-dfs", S,
             "The common answer, and correct, but each node can restart a full comparison."),
            ("In-order strings, substring search", "Search subRoot's in-order string in root's.", "O(m + n)", "O(m + n)", "array-copy", X,
             "Without nulls, different shapes give the same in-order string. What does a match prove?"),
            ("Compare at the first matching value", "Find the first node equal to subRoot's root and compare there.", "O(m + n)", "O(h)", "tree-dfs", X,
             "Values repeat. If the first 4 doesn't match, could a later 4?"),
        ],
    ),
    dict(
        slug="number-of-good-leaf-nodes-pairs", n=1530, title="Number of Good Leaf Nodes Pairs", diff="Medium", topics=["trees"],
        summary="Count pairs of leaves whose shortest path through the tree has length at most distance (distance ≤ 10).",
        example="root = [1, 2, 3, null, 4], distance = 3  →  1",
        criterion="Which approach uses the small distance bound best?",
        hint="Two leaves meet at their lowest common ancestor. What should each subtree tell that ancestor?",
        choices=[
            ("Post-order leaf counts by distance", "Each node returns how many leaves sit at each distance ≤ d; pair left and right counts.", "O(n·d²)", "O(h·d)", "tree-dfs", O,
             "Every pair is counted exactly once, at its lowest common ancestor, by combining two short arrays. The bound d keeps them tiny."),
            ("Every pair through its LCA", "For each pair of leaves, find the LCA and the path length.", "O(L²·h)", "O(n)", "brute", S,
             "Correct, but the number of leaf pairs grows quadratically."),
            ("BFS from every leaf", "Treat the tree as a graph; BFS d steps from each leaf.", "O(L·n)", "O(n)", "graph-bfs", S,
             "Correct, but each leaf explores its neighbourhood again. Combining counts at ancestors shares the work."),
            ("Pairs of sibling leaves", "Count leaves that share a parent.", "O(n)", "O(h)", "tree-dfs", X,
             "Siblings are at distance 2, but larger distances are allowed. What about cousins?"),
        ],
    ),
    dict(
        slug="lcp-67-decorate-tree", n=None, ref="LCP 67", url="https://leetcode.cn/problems/KnLfVT/",
        title="Decorate the Tree", diff="Medium", topics=["trees"],
        summary="Insert a light (a node with value −1) on every parent–child edge of a binary tree. A light between x and its left child becomes x's left child, with the old child as the light's left child; the same on the right. Return the root.",
        example="[7, 5, 6]  →  [7, −1, −1, 5, null, null, 6]",
        criterion="Which approach is linear?",
        hint="For one node, what does decorating its left edge look like? Does that depend on anything below?",
        choices=[
            ("Recurse, wrapping each child in a light", "node.left = Light(left = decorate(node.left)); same on the right.", "O(n)", "O(h)", "tree-dfs", O,
             "Each edge gets exactly one light, and decorating a subtree doesn't depend on anything above it. One visit per node."),
            ("Walk from the root for every edge", "For each original node, find its parent from the root and splice a light in.", "O(n·h)", "O(h)", "brute", S,
             "Correct, but each splice repeats a walk down the tree. Recursion is already standing on the parent."),
            ("Lights above leaves only", "Insert a light only between each leaf and its parent.", "O(n)", "O(h)", "tree-dfs", X,
             "Every node with a parent gets a light, not just the leaves."),
            ("Also wrap the root", "Put a light above the root as well.", "O(n)", "O(h)", "tree-dfs", X,
             "The root has no parent, and the decorated root must keep the original value."),
        ],
    ),
    dict(
        slug="count-univalue-subtrees", n=250, title="Count Univalue Subtrees", diff="Medium", topics=["trees"],
        summary="Count subtrees (a node with all its descendants) in which every node has the same value.",
        example="[5, 1, 5, 5, 5, null, 5]  →  4",
        criterion="Which approach is linear with O(h) extra space?",
        hint="When is a node's subtree univalue, given its children's answers?",
        choices=[
            ("Post-order, check both children", "Evaluate both children first; uni if both are uni and match the node's value.", "O(n)", "O(h)", "tree-dfs", O,
             "Children report whether they're univalue, so the parent decides in O(1). Evaluating both before combining counts every subtree."),
            ("Check every subtree from scratch", "For each node, walk its subtree comparing values.", "O(n²)", "O(h)", "brute", S,
             "Correct, but deep nodes are rechecked for every ancestor."),
            ("Combine with a short-circuit and", "return uni(left) and uni(right) and values match.", "O(n)", "O(h)", "tree-dfs", X,
             "If the left side fails, the right call never runs — and its univalue subtrees never get counted."),
            ("Count the leaves", "Every leaf is univalue; return the leaf count.", "O(n)", "O(h)", "tree-dfs", X,
             "Leaves count, but so do larger subtrees like 5 → 5. What about those?"),
        ],
    ),
    dict(
        slug="count-nodes-equal-to-sum-of-descendants", n=1973, title="Count Nodes Equal to Sum of Descendants", diff="Medium", topics=["trees"],
        summary="Count nodes whose value equals the sum of all their descendants' values (0 if they have none).",
        example="[10, 3, 4, 2, 1]  →  2",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What should a child return so its parent knows the sum of everything below it?",
        choices=[
            ("Post-order returning subtree sums", "Descendant sum = left sum + right sum; compare with val; return it + val.", "O(n)", "O(h)", "tree-dfs", O,
             "The children's subtree sums are exactly the descendants' sum. One pass, constant work per node."),
            ("Sum descendants at every node", "For each node, traverse below it to sum.", "O(n²)", "O(h)", "brute", S,
             "Correct, but deep nodes are added again for every ancestor."),
            ("Compare with the children's values", "Count nodes where val = left.val + right.val.", "O(n)", "O(h)", "tree-dfs", X,
             "Descendants include grandchildren and beyond. In 10 → 3 → (2, 1), does 10 equal 3 + its other child alone?"),
            ("Compare with the subtree sum", "Count nodes where val equals the sum including itself.", "O(n)", "O(h)", "tree-dfs", X,
             "A sum that already contains val only equals val when the descendants add to 0."),
        ],
    ),
    dict(
        slug="equal-tree-partition", n=663, title="Equal Tree Partition", diff="Medium", topics=["trees"],
        summary="Decide whether removing exactly one edge can split the tree into two parts with equal sums. Values may be negative.",
        example="[5, 10, 10, null, null, 2, 3]  →  true",
        criterion="Which approach is linear and handles a total of 0 correctly?",
        hint="Which subtree sums correspond to an edge you can actually cut?",
        choices=[
            ("Subtree sums except the root's", "Post-order every subtree sum, leaving out the whole tree's; check total/2 is among them.", "O(n)", "O(n)", "hashmap", O,
             "Each cut separates a non-root subtree. Leaving out the root's sum matters when the total is 0, because there is no edge above the root."),
            ("Recompute both sides per edge", "For each edge, sum both parts.", "O(n²)", "O(h)", "brute", S,
             "Correct, but each cut rescans the tree."),
            ("All subtree sums, root included", "Check whether total/2 appears among every subtree sum.", "O(n)", "O(n)", "hashmap", X,
             "When the total is 0, the root's own sum 0 equals total/2. Which edge would you cut?"),
            ("Try the root's two edges", "Check only whether a child of the root has sum total/2.", "O(n)", "O(h)", "tree-dfs", X,
             "The right cut can be deep in the tree, as in the example."),
        ],
    ),
    dict(
        slug="maximum-average-subtree", n=1120, title="Maximum Average Subtree", diff="Medium", topics=["trees"],
        summary="Return the maximum average value over all subtrees (a node with all its descendants).",
        example="[5, 6, 1]  →  6.0",
        criterion="Which approach is linear with O(h) extra space?",
        hint="What two numbers about a subtree combine cleanly with its sibling's?",
        choices=[
            ("Post-order returning (sum, count)", "Combine sums and counts; track the best sum / count.", "O(n)", "O(h)", "tree-dfs", O,
             "Sums and counts add across children, so each average comes in O(1). One pass covers every subtree."),
            ("Recompute each subtree", "For each node, traverse its subtree to average it.", "O(n²)", "O(h)", "brute", S,
             "Correct, but nodes are recounted for every ancestor."),
            ("Average of the children's averages", "Combine (val + avg(left) + avg(right)) / 3.", "O(n)", "O(h)", "tree-dfs", X,
             "Subtrees of different sizes can't be averaged like that. A 1-node and a 9-node subtree shouldn't weigh the same."),
            ("Largest value in the tree", "Return the maximum node value.", "O(n)", "O(h)", "tree-dfs", X,
             "Only leaves stand alone as subtrees. In [10, 1], can 10 be averaged without 1?"),
        ],
    ),
    dict(
        slug="count-nodes-that-are-great-enough", n=2792, title="Count Nodes That Are Great Enough", diff="Hard", topics=["trees", "data-structures"],
        summary="A node is great enough if its subtree has at least k nodes and its value is greater than the values of at least k nodes in its subtree. Count such nodes (k ≤ 10).",
        example="root = [7, 6, 5, 4, 3, 2, 1], k = 2  →  3",
        criterion="Which approach uses the small k best?",
        hint="To beat at least k values, which values of the subtree do you actually need to know?",
        choices=[
            ("Post-order keeping the k smallest", "Each subtree returns its k smallest values (merge children's, add own, trim to k).", "O(n·k log k)", "O(h·k)", "heap", O,
             "Beating k values means beating the k-th smallest. Merging two short lists per node keeps that information at O(k) size."),
            ("Collect and sort every subtree", "For each node, gather all its subtree's values and sort them.", "O(n² log n)", "O(n)", "sort", S,
             "Correct, but each value is copied once per ancestor. Only the k smallest ever matter."),
            ("Compare with the children only", "Great enough if val beats its children.", "O(n)", "O(h)", "tree-dfs", X,
             "It needs to beat k values anywhere in its subtree — and the subtree must have at least k nodes."),
            ("Node is its subtree's maximum", "Count nodes larger than everything below, with size ≥ k.", "O(n)", "O(h)", "tree-dfs", X,
             "It only has to beat k values, not all of them."),
        ],
    ),
    dict(
        slug="largest-bst-subtree", n=333, title="Largest BST Subtree", diff="Medium", topics=["trees"],
        summary="Return the size of the largest subtree (a node with all its descendants) that is a valid binary search tree.",
        example="[10, 5, 15, 1, 8, null, 7]  →  3",
        criterion="Which approach is linear?",
        hint="What must a parent know about each child subtree to decide whether it is a BST?",
        choices=[
            ("Post-order (isBST, min, max, size)", "A node is a BST if both children are and left.max < val < right.min.", "O(n)", "O(h)", "tree-dfs", O,
             "The children's min, max and size are all the parent needs, so each node is decided in O(1)."),
            ("Validate from every node", "Run a BST check on each node's subtree.", "O(n²)", "O(h)", "brute", S,
             "Correct, but every subtree is revalidated for each ancestor."),
            ("Parent–child ordering only", "Count subtrees where every left child < parent < right child.", "O(n)", "O(h)", "tree-dfs", X,
             "A node deep in the right subtree must still exceed the root. Do local checks see that?"),
            ("Longest increasing run in-order", "Take the longest strictly increasing stretch of the in-order list.", "O(n)", "O(n)", "array-copy", X,
             "An increasing stretch can mix nodes from different subtrees. Is it one subtree?"),
        ],
    ),
    dict(
        slug="find-leaves-of-binary-tree", n=366, title="Find Leaves of Binary Tree", diff="Medium", topics=["trees"],
        summary="Repeatedly collect and remove all leaves until the tree is empty. Return the groups in removal order.",
        example="[1, 2, 3, 4, 5]  →  [[4, 5, 3], [2], [1]]",
        criterion="Which approach is linear without modifying the tree?",
        hint="In which round is a node removed, in terms of its children?",
        choices=[
            ("Group by height (leaf = 0)", "Post-order height = 1 + max(children); append the node to group[height].", "O(n)", "O(h)", "tree-dfs", O,
             "A node is removed one round after its last child, so its round is its height. One pass places every node."),
            ("Simulate the rounds", "Each round, find and detach the current leaves.", "O(n·h)", "O(h)", "brute", S,
             "Correct, but every round rescans the tree — and it destroys it."),
            ("Group by depth, deepest first", "Level order, then reverse the levels.", "O(n)", "O(w)", "tree-bfs", X,
             "Node 3 is at depth 1 but it's a leaf, so it goes in the first round. Does depth decide the round?"),
            ("Group by subtree size", "Order nodes by how many descendants they have.", "O(n)", "O(h)", "tree-dfs", X,
             "A node above two leaves and a node above a single leaf are both removed in round 2, yet their sizes differ."),
        ],
    ),
    dict(
        slug="binary-tree-upside-down", n=156, title="Binary Tree Upside Down", diff="Medium", topics=["trees"],
        summary="Every right node is a leaf with a left sibling, or empty. Turn the tree upside down: each left child becomes the parent, its old parent the new right child, and the old right sibling the new left child.",
        example="[1, 2, 3, 4, 5]  →  [4, 5, 2, null, null, 3, 1]",
        criterion="Which approach uses O(1) extra space?",
        hint="Walk down the left spine. At each step, which three pointers need to change?",
        choices=[
            ("Iterative relink down the left spine", "Track prev and prevRight; set node.left = prevRight, node.right = prev.", "O(n)", "O(1)", "linked-list", O,
             "Like reversing a linked list along the left spine, carrying the old right sibling along. Only a few pointers are needed."),
            ("Recursive relink", "Recurse to the leftmost node, then relink on the way back.", "O(n)", "O(h)", "recursion", S,
             "Correct and natural, but the recursion stack holds the whole left spine."),
            ("Mirror the tree", "Swap the children of every node.", "O(n)", "O(h)", "tree-dfs", X,
             "Mirroring keeps the root at the top. The leftmost node is supposed to become the new root."),
            ("Repeated right rotations at the root", "Rotate right until the leftmost node is at the top.", "O(n)", "O(1)", "tree-dfs", X,
             "A right rotation moves 2's old right child under 1. In the upside-down tree, which nodes become 2's children?"),
        ],
    ),
    dict(
        slug="check-if-two-expression-trees-are-equivalent", n=1612, title="Check If Two Expression Trees are Equivalent", diff="Medium", topics=["trees"],
        summary="Two expression trees use only '+' and single-letter variables. Decide whether they evaluate to the same value for every assignment of the variables.",
        example="a + (b + c)  and  (b + c) + a  →  true",
        criterion="Which approach is linear and always right?",
        hint="With only addition, what does an expression's value depend on?",
        choices=[
            ("Count each variable's leaves", "Tally letters at the leaves of both trees and compare the 26 counts.", "O(n)", "O(h)", "counting", O,
             "Addition is commutative and associative, so the value depends only on how many times each variable appears."),
            ("Sort the leaves and compare", "Collect both leaf lists, sort, compare.", "O(n log n)", "O(n)", "sort", S,
             "Correct, but with only 26 letters, counting does the same without sorting."),
            ("Structural match with child swaps", "Equal if the trees match, allowing children to be swapped.", "O(n)", "O(h)", "tree-dfs", X,
             "a + (b + c) and (a + b) + c are equal, but no swap turns one shape into the other."),
            ("Evaluate on random values", "Assign random numbers to variables and compare the results.", "O(n)", "O(h)", "math", X,
             "Different expressions can agree on a particular assignment. Can a few trials prove equality?"),
        ],
    ),
]
