"""Pilot question bank.

Summaries are original paraphrases; the full problem lives at `source_url`.
Each question has exactly one optimal choice. Approaches that would tie with
the optimal one under the stated criterion are deliberately left out.

Choice tuple: (label, detail, time, space, visual, verdict, socratic explanation)
verdict: O = optimal, S = valid but suboptimal, X = incorrect
"""

O, S, X = "optimal", "suboptimal", "incorrect"

LC = "https://leetcode.com/problems/{}/"

QUESTIONS = [
    # ---------------------------------------------------------------- Arrays & Hashing
    dict(
        slug="two-sum", n=1, title="Two Sum", diff="Easy", topics=["data-structures"],
        summary="Given an unsorted integer array and a target, return the indices of the two entries that add up to the target. Exactly one pair works.",
        example="nums = [2, 7, 11, 15], target = 9  →  [0, 1]",
        criterion="Which approach is best when n is up to 10⁴ and you must return original indices?",
        hint="For each number x, what single value would you need to have seen already?",
        choices=[
            ("Hash map, one pass", "Store value → index; for each x, look up target − x before inserting x.", "O(n)", "O(n)", "hashmap", O,
             "What do you need to know when you reach x? Only whether target − x appeared earlier. A hash map answers that in O(1), so one pass is enough."),
            ("Sort + two pointers", "Sort (value, index) pairs, then move pointers inward from both ends.", "O(n log n)", "O(n)", "two-pointers", S,
             "This works if you keep the original indices, but why pay for sorting when a lookup table avoids ordering altogether?"),
            ("Check every pair", "Nested loops over i < j, test nums[i] + nums[j].", "O(n²)", "O(1)", "brute", S,
             "Correct, but how many pairs is that at n = 10⁴? About 5·10⁷ — the repeated searching is exactly what a hash map removes."),
            ("Binary search for complement", "For each x, binary search the array for target − x.", "O(n log n)", "O(1)", "binary-search", X,
             "Binary search needs sorted input. The array here is unsorted, so what would the search actually return?"),
        ],
    ),
    dict(
        slug="group-anagrams", n=49, title="Group Anagrams", diff="Medium", topics=["data-structures"],
        summary="Group a list of lowercase strings so that words that are anagrams of each other end up in the same group.",
        example='["eat","tea","tan","ate","nat","bat"]  →  [["eat","tea","ate"],["tan","nat"],["bat"]]',
        criterion="Which approach is the standard interview answer for n words of length ≤ k?",
        hint="What canonical form do all anagrams of a word share?",
        choices=[
            ("Hash map keyed by sorted word", "Sort each word's letters and use the result as the map key.", "O(n·k log k)", "O(n·k)", "hashmap", O,
             "What do 'eat', 'tea' and 'ate' have in common? The same sorted letters, 'aet'. Using that as a key groups them in one pass."),
            ("Compare every pair", "For each pair of words, sort both and compare to decide if they belong together.", "O(n²·k log k)", "O(n·k)", "brute", S,
             "It gives correct groups, but why compare pairs when each word can compute its own group key independently?"),
            ("Key by length + char-code sum", "Group words with the same length and the same sum of character codes.", "O(n·k)", "O(n·k)", "math", X,
             "Is the sum unique to a set of letters? 'ad' and 'bc' have equal length and equal sums, but they are not anagrams."),
            ("Union-find over anagram pairs", "Union every pair of words that are anagrams, then collect components.", "O(n²·k)", "O(n)", "union-find", S,
             "Union-find gives the right components, but it still checks all pairs. A canonical key avoids pairing entirely."),
        ],
    ),
    dict(
        slug="top-k-frequent-elements", n=347, title="Top K Frequent Elements", diff="Medium", topics=["data-structures"],
        summary="Return the k values that occur most often in an integer array. The answer is unique.",
        example="nums = [1,1,1,2,2,3], k = 2  →  [1, 2]",
        criterion="Which approach is best when k is much smaller than the number of distinct values?",
        hint="After counting, do you need a full ordering of all values, or only the best k?",
        choices=[
            ("Count + min-heap of size k", "Count with a hash map, keep a min-heap of the k highest counts.", "O(n log k)", "O(n)", "heap", O,
             "Do you need to rank every value? No — only the top k. A size-k heap evicts anything that cannot make the cut, so each step costs log k."),
            ("Count + sort by frequency", "Count with a hash map, sort all distinct values by count.", "O(n log n)", "O(n)", "sort", S,
             "Correct, but sorting orders all distinct values. When k is small, how much of that ordering do you actually use?"),
            ("Pick the max count k times", "Count, then scan the map k times, removing the current max each time.", "O(k·n)", "O(n)", "brute", S,
             "Works, but each of the k passes rescans everything. What structure keeps the best candidates ready?"),
            ("Sort values, take last k distinct", "Sort nums and return the k largest distinct values.", "O(n log n)", "O(n)", "sort", X,
             "Are the largest values the most frequent ones? Not necessarily — this ranks by value, not by count."),
        ],
    ),
    dict(
        slug="product-of-array-except-self", n=238, title="Product of Array Except Self", diff="Medium", topics=["data-structures"],
        summary="For each position, output the product of every other element. Division is not allowed.",
        example="[1, 2, 3, 4]  →  [24, 12, 8, 6]",
        criterion="Which approach meets O(n) time without division, using only the output array as extra space?",
        hint="The answer at i is (product of everything left of i) × (product of everything right of i).",
        choices=[
            ("Prefix × suffix products", "Fill output with left products, then sweep right-to-left multiplying a running suffix.", "O(n)", "O(1) extra", "prefix", O,
             "Can you split 'everything except i' into two parts you can build incrementally? Left products and right products — two sweeps, no division."),
            ("Total product ÷ nums[i]", "Multiply everything once, divide by each element.", "O(n)", "O(1)", "math", X,
             "Division is disallowed, and what happens when the array contains a zero?"),
            ("Multiply all others per index", "For each i, loop over every j ≠ i.", "O(n²)", "O(1)", "brute", S,
             "Correct, but notice how much multiplication is repeated between i and i+1. Could you reuse it?"),
            ("Segment tree of products", "Build a product segment tree; query [0,i) and (i,n) for each i.", "O(n log n)", "O(n)", "tree-dfs", S,
             "It works, but the queries are always prefixes and suffixes. Do you need a general range structure for that?"),
        ],
    ),
    dict(
        slug="longest-consecutive-sequence", n=128, title="Longest Consecutive Sequence", diff="Medium", topics=["data-structures"],
        summary="Find the length of the longest run of consecutive integers that can be formed from the values of an unsorted array.",
        example="[100, 4, 200, 1, 3, 2]  →  4  (1, 2, 3, 4)",
        criterion="The problem requires O(n) time. Which approach meets it?",
        hint="How can you tell that a number is the start of a run?",
        choices=[
            ("Hash set, count from run starts", "Put values in a set; only when x − 1 is absent, count x, x+1, … .", "O(n)", "O(n)", "set", O,
             "If x − 1 is in the set, is x ever a run start? No. Counting only from starts means each value is visited a constant number of times."),
            ("Sort, then scan", "Sort, skip duplicates, and track the current run length.", "O(n log n)", "O(1)", "sort", S,
             "Correct and simple, but does it meet the O(n) requirement? Sorting alone costs n log n."),
            ("Count upward from every value", "Use a set, but start counting x, x+1, … from every value.", "O(n²)", "O(n)", "brute", S,
             "Correct, but a run of length L gets recounted from each of its members. What check would avoid that?"),
            ("Two pointers on the raw array", "Move left/right pointers while neighbors differ by 1.", "O(n)", "O(1)", "two-pointers", X,
             "Consecutive values need not be adjacent in an unsorted array. What would the pointers be comparing?"),
        ],
    ),
    # ---------------------------------------------------------------- Two Pointers
    dict(
        slug="valid-palindrome", n=125, title="Valid Palindrome", diff="Easy", topics=["sliding-window"],
        summary="Decide whether a string reads the same forward and backward after lowercasing and ignoring non-alphanumeric characters.",
        example='"A man, a plan, a canal: Panama"  →  true',
        criterion="Which approach uses O(1) extra space?",
        hint="Compare characters from both ends while skipping the ones that don't count.",
        choices=[
            ("Two pointers from both ends", "Move i forward and j backward, skipping non-alphanumerics, compare lowercased chars.", "O(n)", "O(1)", "two-pointers", O,
             "Do you need a cleaned copy to compare the ends? No — skip invalid characters in place and compare as you go."),
            ("Clean copy vs. its reverse", "Build a filtered lowercase string and compare it to its reverse.", "O(n)", "O(n)", "array-copy", S,
             "Correct and readable, but it allocates two extra strings. Can you compare without building them?"),
            ("Recursively strip the ends", "Check first/last char, recurse on the sliced middle.", "O(n²)", "O(n²)", "recursion", S,
             "It's correct, but each slice copies the string. How much copying happens over n/2 levels?"),
            ("At most one odd letter count", "Count characters; valid if at most one has an odd count.", "O(n)", "O(1)", "hashmap", X,
             "That tests whether the letters could be rearranged into a palindrome. 'aab' passes the count test, but it isn't one."),
        ],
    ),
    dict(
        slug="3sum", n=15, title="3Sum", diff="Medium", topics=["sliding-window"],
        summary="Return all unique triplets in an array whose values sum to zero.",
        example="[-1, 0, 1, 2, -1, -4]  →  [[-1, -1, 2], [-1, 0, 1]]",
        criterion="Which approach is the standard answer, handling duplicates cleanly with O(1) extra space?",
        hint="Fix one number; the remaining problem is Two Sum on a sorted array.",
        choices=[
            ("Sort + fix one + two pointers", "Sort; for each i, move l/r inward on the rest, skipping duplicates.", "O(n²)", "O(1) extra", "two-pointers", O,
             "Once sorted, what does Two Sum become? A two-pointer sweep. Sorting also puts duplicates next to each other so skipping them is trivial."),
            ("Pairs + hash lookup", "For each pair, check a hash set for the negated sum; dedupe with a set of triplets.", "O(n²)", "O(n)", "hashmap", S,
             "Same time bound, but it needs extra memory and fiddly deduplication. What does sorting give you for free?"),
            ("Three nested loops", "Try every triplet; store sorted triplets in a set.", "O(n³)", "O(n)", "brute", S,
             "Correct, but at n = 3000 that's billions of triplets. Which inner loop can be replaced by pointers?"),
            ("Sliding window of size 3", "Sort, then check each window of three adjacent values.", "O(n)", "O(1)", "sliding-window", X,
             "Must the three values be adjacent? [-4, …, 1, …, 3] can sum to zero with gaps between them."),
        ],
    ),
    dict(
        slug="container-with-most-water", n=11, title="Container With Most Water", diff="Medium", topics=["sliding-window"],
        summary="Given vertical line heights, pick two lines that together with the x-axis hold the most water. Area = width × shorter height.",
        example="[1, 8, 6, 2, 5, 4, 8, 3, 7]  →  49",
        criterion="Which approach is best for n up to 10⁵?",
        hint="If you start as wide as possible, which side can you safely give up?",
        choices=[
            ("Two pointers, move the shorter side", "Start at both ends; record area; move the pointer at the shorter line inward.", "O(n)", "O(1)", "two-pointers", O,
             "Can moving the taller line ever help? The width shrinks and the height is still capped by the shorter line — so only moving the shorter one can improve."),
            ("Check every pair", "Compute the area for every i < j.", "O(n²)", "O(1)", "brute", S,
             "Correct, but at 10⁵ lines that's ~5·10⁹ pairs. Which pairs can you prove are never better?"),
            ("Pair the two tallest lines", "Sort heights descending and use the two tallest.", "O(n log n)", "O(n)", "sort", X,
             "Area also depends on width. Two tall lines next to each other can hold less than two medium lines far apart."),
            ("Prefix/suffix max water formula", "Sum min(leftMax, rightMax) − h over all positions.", "O(n)", "O(n)", "prefix", X,
             "That formula solves Trapping Rain Water. Here you pick only two lines; is the answer a sum over all positions?"),
        ],
    ),
    dict(
        slug="trapping-rain-water", n=42, title="Trapping Rain Water", diff="Hard", topics=["sliding-window", "monotonic-stack"],
        summary="Given bar heights, compute how much rain water is trapped between the bars after it rains.",
        example="[0,1,0,2,1,0,1,3,2,1,2,1]  →  6",
        criterion="Which approach is best using O(1) extra space?",
        hint="Water above a bar is min(max to its left, max to its right) − its height.",
        choices=[
            ("Two pointers with running maxes", "Move the side with the smaller max inward, adding max − height.", "O(n)", "O(1)", "two-pointers", O,
             "If leftMax < rightMax, is the water at the left pointer already decided? Yes — the left side is the bottleneck. That lets you drop the arrays."),
            ("Prefix-max and suffix-max arrays", "Precompute leftMax[] and rightMax[], then sum.", "O(n)", "O(n)", "prefix", S,
             "Correct and a good stepping stone, but can you avoid storing both arrays?"),
            ("Scan both sides for every bar", "For each bar, scan left and right to find the maxima.", "O(n²)", "O(1)", "brute", S,
             "Correct, but it recomputes the same maxima over and over. What could you carry along instead?"),
            ("Two pointers, move the taller side", "Same as above but advance the pointer with the larger max.", "O(n)", "O(1)", "two-pointers", X,
             "Which side's water level is guaranteed? Only the side with the smaller max. Moving the taller side adds water you can't justify."),
        ],
    ),
    # ---------------------------------------------------------------- Stack
    dict(
        slug="valid-parentheses", n=20, title="Valid Parentheses", diff="Easy", topics=["data-structures"],
        summary="Decide whether a string of ()[]{} brackets is properly opened and closed in the right order.",
        example='"([]{})" → true,   "([)]" → false',
        criterion="Which approach is correct and linear?",
        hint="When you see a closing bracket, which opening bracket must it match?",
        choices=[
            ("Stack of open brackets", "Push openers; on a closer, pop and check it matches.", "O(n)", "O(n)", "stack", O,
             "A closer must match the most recent unmatched opener — last in, first out. That is exactly a stack."),
            ("Count each bracket type", "Valid if each type has equal opens and closes.", "O(n)", "O(1)", "counting", X,
             "What does counting say about '([)]'? The counts balance, but the order is wrong."),
            ("Repeatedly delete (), [], {}", "Remove adjacent matching pairs until none remain.", "O(n²)", "O(n)", "brute", S,
             "It gives the right answer, but each pass rescans the string. A stack does the same cancellation in one pass."),
            ("Split in half and mirror-check", "Check that the second half mirrors the first.", "O(n)", "O(1)", "two-pointers", X,
             "Is '()()' a mirror of itself? No, yet it's valid. Nesting isn't the only valid shape."),
        ],
    ),
    dict(
        slug="daily-temperatures", n=739, title="Daily Temperatures", diff="Medium", topics=["monotonic-stack"],
        summary="For each day, find how many days you'd wait for a warmer temperature (0 if never).",
        example="[73,74,75,71,69,72,76,73]  →  [1,1,4,2,1,1,0,0]",
        criterion="Which approach is best for n up to 10⁵?",
        hint="Which days are still 'waiting' for a warmer day, and in what order do they get answered?",
        choices=[
            ("Monotonic decreasing stack", "Keep indices of unresolved days; pop while today is warmer and record the gap.", "O(n)", "O(n)", "monotonic-stack", O,
             "Waiting days always have non-increasing temperatures, so a warmer day resolves them from the top. Each index is pushed and popped once."),
            ("Scan forward for each day", "For every day, look ahead until a warmer day appears.", "O(n²)", "O(1)", "brute", S,
             "Correct, but a long cooling streak makes every day scan far ahead. Which work is repeated?"),
            ("Min-heap of pending days", "Push (temp, idx); each day pop all cooler entries and answer them.", "O(n log n)", "O(n)", "heap", S,
             "It's correct, but do you need a heap? The pending days are already in sorted order — a stack keeps that for free."),
            ("Next larger value in sorted order", "Sort temperatures; the answer is the index gap to the next larger value.", "O(n log n)", "O(n)", "sort", X,
             "The next larger value in sorted order might occur earlier in time. Does sorting keep 'future days only'?"),
        ],
    ),
    dict(
        slug="min-stack", n=155, title="Min Stack", diff="Medium", topics=["data-structures"],
        summary="Design a stack supporting push, pop, top and getMin, each in constant time.",
        example="push(-2), push(0), push(-3), getMin() → -3, pop(), getMin() → -2",
        criterion="All four operations must be O(1).",
        hint="If you pop the current minimum, how do you know the previous one?",
        choices=[
            ("Store (value, min so far) pairs", "Each entry remembers the minimum of the stack at that height.", "O(1) each", "O(n)", "stack", O,
             "What was the minimum before this push? Store it alongside the value, and popping restores it automatically."),
            ("Scan on getMin", "Plain stack; getMin looks through all elements.", "O(n) getMin", "O(n)", "brute", S,
             "Correct, but getMin isn't O(1). What could you precompute at push time?"),
            ("Single global min variable", "Update min on push; keep it on pop.", "O(1)", "O(1)", "math", X,
             "Push 1, push 0, pop. What is min now? The variable still says 0, but 0 is gone."),
            ("Stack + sorted multiset", "Mirror values in a balanced BST for min lookups.", "O(log n)", "O(n)", "tree-dfs", S,
             "Correct, but log n per operation. Only the minimum matters, and the stack's order already tells you when it changes."),
        ],
    ),
    # ---------------------------------------------------------------- Binary Search
    dict(
        slug="binary-search", n=704, title="Binary Search", diff="Easy", topics=["binary-search"],
        summary="Return the index of a target in a sorted array of distinct integers, or −1 if absent.",
        example="nums = [-1,0,3,5,9,12], target = 9  →  4",
        criterion="The solution must run in O(log n).",
        hint="What does comparing with the middle element tell you about half of the array?",
        choices=[
            ("Classic binary search", "Keep lo/hi; compare with mid and discard half each step.", "O(log n)", "O(1)", "binary-search", O,
             "Because the array is sorted, one comparison with the middle rules out half the candidates. That halving is what gives log n."),
            ("Linear scan", "Check each element in order.", "O(n)", "O(1)", "brute", S,
             "Correct, but it ignores the sorted order. What information are you throwing away?"),
            ("Jump search in √n blocks", "Jump ahead √n at a time, then scan the block.", "O(√n)", "O(1)", "sliding-window", S,
             "Better than linear, but still not logarithmic. Why jump by a fixed step when you can halve?"),
            ("Build a value → index map", "Put every element in a hash map, then look up the target.", "O(n)", "O(n)", "hashmap", S,
             "One lookup is O(1), but building the map reads the whole array. Is that under O(log n)?"),
        ],
    ),
    dict(
        slug="search-in-rotated-sorted-array", n=33, title="Search in Rotated Sorted Array", diff="Medium", topics=["binary-search"],
        summary="A sorted array of distinct values was rotated at an unknown pivot. Find the index of a target, or −1.",
        example="[4,5,6,7,0,1,2], target = 0  →  4",
        criterion="The solution must run in O(log n).",
        hint="At any mid, at least one of the two halves is still properly sorted.",
        choices=[
            ("Binary search on the sorted half", "At each mid, find which half is sorted and check if the target lies in it.", "O(log n)", "O(1)", "binary-search", O,
             "Can you always tell which half is sorted? Yes, by comparing nums[lo] with nums[mid]. Then a range check tells you where to go."),
            ("Plain binary search", "Ignore the rotation and search as if the array were sorted.", "O(log n)", "O(1)", "binary-search", X,
             "After rotation, is 'target < mid → go left' still true? Not across the pivot — you'd discard the half holding the target."),
            ("Linear scan", "Check each element.", "O(n)", "O(1)", "brute", S,
             "Correct, but it misses the O(log n) requirement. What sortedness is still left to exploit?"),
            ("Hash map of value → index", "Index all values, then look up the target.", "O(n)", "O(n)", "hashmap", S,
             "Building the map already reads every element, so the requirement is lost before the lookup."),
        ],
    ),
    dict(
        slug="koko-eating-bananas", n=875, title="Koko Eating Bananas", diff="Medium", topics=["binary-search"],
        summary="Koko eats up to k bananas per hour from one pile at a time. Find the minimum k that finishes all piles within h hours.",
        example="piles = [3,6,7,11], h = 8  →  4",
        criterion="Which approach is best when pile sizes go up to 10⁹?",
        hint="If speed k works, does every speed above k also work?",
        choices=[
            ("Binary search on speed", "Search k in [1, max(pile)]; check total hours = Σ⌈p/k⌉ ≤ h.", "O(n log m)", "O(1)", "binary-search", O,
             "Feasibility is monotonic in k: faster never hurts. That means you can binary search on the answer instead of the array."),
            ("Try k = 1, 2, 3, …", "Increase k until the hours fit.", "O(n·m)", "O(1)", "brute", S,
             "Correct, but m can be 10⁹. Since feasibility only flips once, do you need to try every k?"),
            ("k = ⌈sum / h⌉", "Divide total bananas evenly across hours.", "O(n)", "O(1)", "math", X,
             "Koko can't split an hour between piles. With [3,6,7,11] and h = 8, ⌈27/8⌉ = 4 happens to work — try piles = [5,5], h = 3."),
            ("Greedy on the largest pile", "Use a max-heap and eat the biggest pile first.", "O(n log n)", "O(n)", "heap", X,
             "The order Koko eats piles doesn't change the total hours. What quantity are you actually minimizing?"),
        ],
    ),
    # ---------------------------------------------------------------- Sliding Window
    dict(
        slug="best-time-to-buy-and-sell-stock", n=121, title="Best Time to Buy and Sell Stock", diff="Easy", topics=["data-structures", "dp"],
        summary="Given daily prices, choose one day to buy and a later day to sell for maximum profit (0 if no profit is possible).",
        example="[7, 1, 5, 3, 6, 4]  →  5",
        criterion="Which approach is best for n up to 10⁵?",
        hint="On each day, what's the best price you could have bought at?",
        choices=[
            ("Track the minimum so far", "One pass: profit = price − min price seen so far.", "O(n)", "O(1)", "sliding-window", O,
             "If you sell today, the best buy is the cheapest earlier day. Keeping that running minimum answers every day in one pass."),
            ("Check every buy/sell pair", "Nested loops over i < j.", "O(n²)", "O(1)", "brute", S,
             "Correct, but for each sell day you re-find the cheapest earlier price. Could you remember it instead?"),
            ("Global max − global min", "Subtract the overall lowest price from the overall highest.", "O(n)", "O(1)", "math", X,
             "What if the highest price comes before the lowest? You can't sell before you buy."),
            ("Sort prices", "Sort and take last − first.", "O(n log n)", "O(1)", "sort", X,
             "Sorting destroys the time order, which is the whole constraint."),
        ],
    ),
    dict(
        slug="longest-substring-without-repeating-characters", n=3, title="Longest Substring Without Repeating Characters", diff="Medium", topics=["sliding-window"],
        summary="Find the length of the longest contiguous substring that has no repeated characters.",
        example='"abcabcbb"  →  3  ("abc")',
        criterion="Which approach is best for strings up to 5·10⁴ characters?",
        hint="When you hit a repeat, where must the new window start?",
        choices=[
            ("Sliding window + last-seen map", "Expand right; on a repeat, jump left past the character's previous index.", "O(n)", "O(Σ)", "sliding-window", O,
             "When s[r] repeats, any window containing both copies is invalid — so left can jump straight past the old copy. Each index moves forward only."),
            ("Extend from every start", "For each start, grow with a set until a repeat.", "O(n²)", "O(Σ)", "brute", S,
             "Correct, but after a repeat you restart from the next index and recheck the same characters. Why throw that work away?"),
            ("Check every substring", "Generate all substrings and test uniqueness.", "O(n³)", "O(Σ)", "brute", S,
             "Correct but cubic. Which substrings can you rule out without testing them?"),
            ("Count distinct characters", "Return the number of distinct characters in s.", "O(n)", "O(Σ)", "set", X,
             "'pwwkew' has 4 distinct letters, but the longest repeat-free substring is 'wke' (3). Distinct counts ignore contiguity."),
        ],
    ),
    dict(
        slug="minimum-window-substring", n=76, title="Minimum Window Substring", diff="Hard", topics=["sliding-window"],
        summary="Find the shortest substring of s that contains every character of t (with multiplicity).",
        example='s = "ADOBECODEBANC", t = "ABC"  →  "BANC"',
        criterion="Which approach is best for |s|, |t| up to 10⁵?",
        hint="Grow the window until it's valid, then shrink it while it stays valid.",
        choices=[
            ("Variable window with need/have counts", "Expand right until all needed counts are met, then shrink left while valid.", "O(|s|+|t|)", "O(Σ)", "sliding-window", O,
             "Once a window is valid, is any longer window with the same left end useful? No — so shrink from the left. Each pointer only moves forward."),
            ("Binary search on window length", "For length L, slide a fixed window and test validity; search the smallest valid L.", "O(|s| log |s|)", "O(Σ)", "binary-search", S,
             "Valid, since a longer window never loses characters. But the variable window finds the answer in a single linear pass."),
            ("Check every substring", "Test all O(n²) substrings.", "O(n²·Σ)", "O(Σ)", "brute", S,
             "Correct, but hopeless at 10⁵. Which windows can you skip once you know one is valid?"),
            ("Fixed window of length |t|", "Slide a window exactly as long as t.", "O(|s|)", "O(Σ)", "sliding-window", X,
             "Must the answer be exactly |t| long? 'BANC' is longer than 'ABC' — extra characters in between are allowed."),
        ],
    ),
    # ---------------------------------------------------------------- Linked List
    dict(
        slug="reverse-linked-list", n=206, title="Reverse Linked List", diff="Easy", topics=["trees"],
        summary="Reverse a singly linked list and return the new head.",
        example="1 → 2 → 3 → 4 → 5  →  5 → 4 → 3 → 2 → 1",
        criterion="Which approach uses O(1) extra space?",
        hint="As you walk, what do you need to remember so you don't lose the rest of the list?",
        choices=[
            ("Iterative prev/curr pointers", "Save next, point curr.next to prev, advance both.", "O(n)", "O(1)", "linked-list", O,
             "Each node only needs its arrow flipped. Keeping prev and next lets you do that in place with no extra memory."),
            ("Recursive reversal", "Reverse the rest, then hook head behind the old tail.", "O(n)", "O(n)", "recursion", S,
             "Elegant and correct, but every node adds a stack frame. For long lists, where does that memory go?"),
            ("Copy values, write them back", "Collect values into an array, then overwrite nodes in reverse.", "O(n)", "O(n)", "array-copy", S,
             "It produces the right order, but uses an array and rewrites values instead of relinking nodes."),
            ("Swap head and tail", "Exchange the first and last nodes.", "O(n)", "O(1)", "linked-list", X,
             "What happens to the middle nodes? For 1→2→3→4, you'd get 4→2→3→1."),
        ],
    ),
    dict(
        slug="linked-list-cycle", n=141, title="Linked List Cycle", diff="Easy", topics=["trees", "sliding-window"],
        summary="Decide whether a linked list contains a cycle.",
        example="3 → 2 → 0 → -4 → (back to 2)  →  true",
        criterion="Which approach uses O(1) extra space?",
        hint="If two runners go around a track at different speeds, what eventually happens?",
        choices=[
            ("Fast & slow pointers (Floyd)", "Move slow by 1, fast by 2; a cycle makes them meet.", "O(n)", "O(1)", "fast-slow", O,
             "Inside a cycle, the fast pointer gains one step per move on the slow one, so it must catch up. No memory beyond two pointers."),
            ("Hash set of visited nodes", "Store node references; a repeat means a cycle.", "O(n)", "O(n)", "set", S,
             "Correct and easy, but it remembers every node. Can two pointers detect the loop without the set?"),
            ("Detect repeated values", "Track node values; a repeated value means a cycle.", "O(n)", "O(n)", "hashmap", X,
             "Two different nodes can hold the same value. Is 1 → 1 → null a cycle?"),
            ("Count past the expected length", "Walk; if you take more than n steps, it's a cycle.", "O(n)", "O(1)", "brute", X,
             "You don't know n — the list has no stored length, and with a cycle you can't count it."),
        ],
    ),
    dict(
        slug="merge-two-sorted-lists", n=21, title="Merge Two Sorted Lists", diff="Easy", topics=["trees"],
        summary="Merge two sorted linked lists into one sorted list by splicing their nodes together.",
        example="1→2→4 and 1→3→4  →  1→1→2→3→4→4",
        criterion="Which approach is linear with O(1) extra space?",
        hint="At each step, which node should come next?",
        choices=[
            ("Dummy head + splice smaller node", "Compare heads, attach the smaller, advance; append the leftover.", "O(n+m)", "O(1)", "linked-list", O,
             "Both lists are sorted, so the next node is always one of the two heads. A dummy node removes the special case for the first attachment."),
            ("Recursive merge", "Return the smaller head with next = merge(rest).", "O(n+m)", "O(n+m)", "recursion", S,
             "Correct and concise, but it uses one stack frame per node. Is that O(1) space?"),
            ("Collect, sort, rebuild", "Put all values in an array, sort, create a new list.", "O((n+m) log(n+m))", "O(n+m)", "sort", S,
             "Correct, but the inputs are already sorted. Why sort again?"),
            ("Alternate nodes from each list", "Take one node from list 1, then list 2, and repeat.", "O(n+m)", "O(1)", "linked-list", X,
             "With 1→2→3 and 10→20, alternating gives 1,10,2,20,3. Is that sorted?"),
        ],
    ),
    dict(
        slug="lru-cache", n=146, title="LRU Cache", diff="Medium", topics=["trees", "data-structures"],
        summary="Design a fixed-capacity cache where get and put run in O(1) and the least-recently-used key is evicted when full.",
        example="cap=2: put(1), put(2), get(1), put(3) evicts key 2",
        criterion="get and put must both be O(1) on average.",
        hint="You need fast lookup by key and fast reordering by recency.",
        choices=[
            ("Hash map + doubly linked list", "Map key → node; move nodes to the front on use; evict from the tail.", "O(1)", "O(cap)", "linked-list", O,
             "The map finds a node in O(1); the doubly linked list lets you unlink and move it in O(1). Together they cover both needs."),
            ("Hash map + array ordering", "Keep keys in an array ordered by use; move a key on each access.", "O(cap)", "O(cap)", "array-copy", S,
             "Correct eviction, but moving a key inside an array shifts elements. Which structure can move an item in O(1)?"),
            ("Hash map + timestamps", "Store last-used time; on eviction scan for the oldest.", "O(cap) evict", "O(cap)", "hashmap", S,
             "Correct, but eviction scans everything. Can you keep items already ordered by recency?"),
            ("FIFO queue", "Evict the key that was inserted first.", "O(1)", "O(cap)", "queue", X,
             "Insertion order isn't usage order. If key 1 was inserted first but just used, should it be evicted?"),
        ],
    ),
    # ---------------------------------------------------------------- Trees
    dict(
        slug="maximum-depth-of-binary-tree", n=104, title="Maximum Depth of Binary Tree", diff="Easy", topics=["trees"],
        summary="Return the number of nodes on the longest root-to-leaf path of a binary tree.",
        example="[3, 9, 20, null, null, 15, 7]  →  3",
        criterion="Which approach is the standard linear answer?",
        hint="How does a node's depth relate to its children's depths?",
        choices=[
            ("Recursive DFS: 1 + max(children)", "depth(node) = 1 + max(depth(left), depth(right)).", "O(n)", "O(h)", "tree-dfs", O,
             "The answer for a node is built from its children's answers — a natural recursion visiting each node once."),
            ("Follow the leftmost path", "Count nodes while going left from the root.", "O(h)", "O(1)", "tree-dfs", X,
             "What if the deepest leaf is on the right? The left spine can be short."),
            ("log₂(number of nodes)", "Count nodes, then take the logarithm.", "O(n)", "O(h)", "math", X,
             "That only holds for balanced trees. A tree shaped like a linked list has depth n."),
            ("Search from root for every node", "For each node, walk from the root to compute its depth; take the max.", "O(n·h)", "O(h)", "brute", S,
             "Correct, but each walk repeats work shared by ancestors. What if children just asked their parent's depth?"),
        ],
    ),
    dict(
        slug="lowest-common-ancestor-of-a-binary-search-tree", n=235, title="Lowest Common Ancestor of a BST", diff="Medium", topics=["trees"],
        summary="In a binary search tree, find the deepest node that has both given nodes p and q as descendants (a node counts as its own descendant).",
        example="root = [6,2,8,0,4,7,9], p = 2, q = 8  →  6",
        criterion="Which approach best uses the BST property?",
        hint="If both p and q are smaller than the current node, where must their ancestor be?",
        choices=[
            ("Walk down using BST order", "Go left if both are smaller, right if both are larger; otherwise stop.", "O(h)", "O(1)", "binary-search", O,
             "The first node where p and q split to different sides (or equals one of them) is the LCA. The BST ordering tells you the direction without exploring both subtrees."),
            ("General binary-tree LCA recursion", "Recurse into both subtrees; return the node where p and q are found on different sides.", "O(n)", "O(h)", "tree-dfs", S,
             "Correct on any binary tree, but it ignores the ordering. Why search both subtrees when values tell you which one?"),
            ("Store root-to-node paths", "Record the path to p and to q, then find the last common node.", "O(h)", "O(h)", "array-copy", S,
             "Correct, but it stores two paths. Can you walk once and stop at the split point?"),
            ("Node with value ⌊(p+q)/2⌋", "Search for the midpoint value.", "O(h)", "O(1)", "math", X,
             "The LCA's value lies between p and q, but why would it be their exact average? It may not even exist."),
        ],
    ),
    dict(
        slug="validate-binary-search-tree", n=98, title="Validate Binary Search Tree", diff="Medium", topics=["trees"],
        summary="Decide whether a binary tree is a valid BST: every node's left subtree is strictly smaller and right subtree strictly larger.",
        example="[5, 1, 4, null, null, 3, 6]  →  false",
        criterion="Which approach is linear with O(h) extra space?",
        hint="A node deep in the right subtree must still be greater than the root.",
        choices=[
            ("DFS with (low, high) bounds", "Pass allowed range down; left narrows high, right narrows low.", "O(n)", "O(h)", "tree-dfs", O,
             "Each node must respect every ancestor, not just its parent. Carrying the valid range down encodes all those constraints at once."),
            ("Check only parent vs. children", "Valid if left.val < node.val < right.val for every node.", "O(n)", "O(h)", "tree-dfs", X,
             "In [5,1,6,null,null,3,7], each parent–child pair looks fine, but 3 sits in 5's right subtree. Is that allowed?"),
            ("In-order into an array", "Traverse in-order, then check the list is strictly increasing.", "O(n)", "O(n)", "array-copy", S,
             "Correct, but you store every value. Could you compare with just the previous value during traversal?"),
            ("Scan whole subtrees per node", "For each node, find max of left and min of right subtree.", "O(n²)", "O(h)", "brute", S,
             "Correct, but subtrees are rescanned for every ancestor. Bounds passed downward avoid that."),
        ],
    ),
    dict(
        slug="binary-tree-level-order-traversal", n=102, title="Binary Tree Level Order Traversal", diff="Medium", topics=["trees"],
        summary="Return the node values of a binary tree level by level, left to right.",
        example="[3, 9, 20, null, null, 15, 7]  →  [[3], [9, 20], [15, 7]]",
        criterion="Which approach is the standard answer?",
        hint="Which data structure naturally hands you nodes in the order they were discovered?",
        choices=[
            ("BFS with a queue, one level at a time", "Process queue.size() nodes per level, enqueueing their children.", "O(n)", "O(w)", "tree-bfs", O,
             "A queue returns nodes in discovery order, which is level order. Snapshotting the queue size separates one level from the next."),
            ("Pre-order DFS output", "Visit root, left, right and output in that order.", "O(n)", "O(h)", "tree-dfs", X,
             "Pre-order dives down the left side first — you'd see 3, 9, 20 only by luck. Try a deeper left subtree."),
            ("One traversal per depth", "For d = 0..h, walk the tree collecting nodes at depth d.", "O(n·h)", "O(h)", "brute", S,
             "Correct, but the tree is walked once per level. One pass with a queue does all levels together."),
            ("Stack-based traversal", "Replace the queue with a stack.", "O(n)", "O(h)", "stack", X,
             "A stack returns the most recent node first. Does that give left-to-right levels?"),
        ],
    ),
    # ---------------------------------------------------------------- Tries
    dict(
        slug="implement-trie-prefix-tree", n=208, title="Implement Trie (Prefix Tree)", diff="Medium", topics=["data-structures"],
        summary="Design a structure supporting insert(word), search(word) and startsWith(prefix).",
        example='insert("apple"), search("app") → false, startsWith("app") → true',
        criterion="Each operation should cost O(L) for a word of length L.",
        hint="Words that share a prefix could share storage for it.",
        choices=[
            ("Trie nodes with child maps + end flag", "Each node maps a character to a child; mark nodes that end a word.", "O(L)", "O(total chars)", "trie", O,
             "Shared prefixes share a path, so any prefix query is just walking L edges from the root."),
            ("Hash set; scan for prefixes", "search is a set lookup; startsWith checks every stored word.", "O(N·L) prefix", "O(total chars)", "set", S,
             "search is fast, but startsWith scans all N words. What structure organizes words by prefix?"),
            ("Sorted list + binary search", "Keep words sorted; binary search for the prefix's position.", "O(L log N)", "O(total chars)", "binary-search", S,
             "Correct for queries, but inserting into a sorted list shifts elements, and each query still pays log N comparisons."),
            ("One concatenated string + find()", "Append all words into one string and search it.", "O(total chars)", "O(total chars)", "array-copy", X,
             "After inserting 'car' and 'pet', would 'rpe' be found? Matches can span word boundaries."),
        ],
    ),
    dict(
        slug="word-search-ii", n=212, title="Word Search II", diff="Hard", topics=["data-structures", "trees"],
        summary="Given a letter grid and a list of words, return every word that can be traced through adjacent cells without reusing a cell.",
        example='board 4×4, words = ["oath","pea","eat","rain"]  →  ["eat","oath"]',
        criterion="Which approach scales to 3·10⁴ words?",
        hint="How can one DFS check many words at once?",
        choices=[
            ("Trie of words + one grid DFS", "Build a trie; DFS from each cell following trie edges, pruning dead prefixes.", "O(m·n·3^L)", "O(total chars)", "trie", O,
             "A trie lets a single DFS track all words sharing a prefix, and it stops the moment no word continues. The word count no longer multiplies the search."),
            ("Word Search I for each word", "Run a separate grid DFS for every word.", "O(W·m·n·3^L)", "O(L)", "backtrack", S,
             "Correct, but with 3·10⁴ words you repeat nearly the same DFS thousands of times."),
            ("Sorted words + binary-searched prefixes", "DFS the grid; at each step binary search the sorted list to check the prefix exists.", "O(m·n·3^L·L log W)", "O(total chars)", "binary-search", S,
             "It prunes correctly, but every step pays a binary search with string comparisons. A trie step is O(1)."),
            ("BFS allowing cell reuse", "BFS from each cell over neighbors, matching letters.", "O(m·n·W)", "O(m·n)", "graph-bfs", X,
             "The rules forbid reusing a cell in one word. Plain BFS can't track per-path visited cells."),
        ],
    ),
    # ---------------------------------------------------------------- Heap
    dict(
        slug="kth-largest-element-in-an-array", n=215, title="Kth Largest Element in an Array", diff="Medium", topics=["data-structures"],
        summary="Return the k-th largest value in an unsorted array (by sorted position, duplicates count).",
        example="[3,2,1,5,6,4], k = 2  →  5",
        criterion="Which approach is the standard answer with guaranteed performance when k ≪ n?",
        hint="Do you need all values ordered, or just a running set of the k best?",
        choices=[
            ("Min-heap of size k", "Push each value; pop when size exceeds k; the top is the answer.", "O(n log k)", "O(k)", "heap", O,
             "The heap's smallest element is the k-th largest seen so far. Anything smaller can never matter, so the heap stays tiny."),
            ("Sort, take index k−1 from the end", "Sort the whole array.", "O(n log n)", "O(1)", "sort", S,
             "Correct and short, but you order all n elements to read one. How much of that is needed?"),
            ("Remove the max k times", "Scan for the max, remove it, repeat k times.", "O(n·k)", "O(1)", "brute", S,
             "Correct, but each round rescans. A heap keeps candidates organized between rounds."),
            ("Put values in a set, then rank", "Deduplicate into a sorted set and take the k-th largest.", "O(n log n)", "O(n)", "set", X,
             "Duplicates count here: in [3,3,1], the 2nd largest is 3. A set would say 1."),
        ],
    ),
    dict(
        slug="merge-k-sorted-lists", n=23, title="Merge k Sorted Lists", diff="Hard", topics=["data-structures", "trees"],
        summary="Merge k sorted linked lists into one sorted linked list.",
        example="[1→4→5, 1→3→4, 2→6]  →  1→1→2→3→4→4→5→6",
        criterion="Which approach is best for N total nodes across k lists?",
        hint="At every step, the next node is the smallest among k candidates.",
        choices=[
            ("Min-heap of list heads", "Push each head; pop the smallest, append it, push its next.", "O(N log k)", "O(k)", "heap", O,
             "Only the k current heads can be next. A heap returns the smallest in log k, and each node passes through it once."),
            ("Merge lists one at a time", "Fold: merge list 1 with 2, the result with 3, and so on.", "O(N·k)", "O(1)", "linked-list", S,
             "Correct, but early nodes get re-walked in every later merge. Could you compare all heads at once?"),
            ("Collect all values and sort", "Dump into an array, sort, rebuild a list.", "O(N log N)", "O(N)", "sort", S,
             "Correct, but each list is already sorted — that structure is wasted."),
            ("Concatenate the lists", "Link the tail of each list to the next head.", "O(N)", "O(1)", "linked-list", X,
             "1→4→5 followed by 1→3→4 isn't sorted. Concatenation ignores values across lists."),
        ],
    ),
    dict(
        slug="k-closest-points-to-origin", n=973, title="K Closest Points to Origin", diff="Medium", topics=["data-structures"],
        summary="Return the k points closest to (0, 0) by Euclidean distance.",
        example="[[1,3], [-2,2]], k = 1  →  [[-2,2]]",
        criterion="Which approach is best when k ≪ n?",
        hint="Keep only the best k seen so far — which one do you throw out?",
        choices=[
            ("Max-heap of size k by distance", "Push each point; pop the farthest when size exceeds k.", "O(n log k)", "O(k)", "heap", O,
             "The farthest of your current k is the one to evict. A max-heap exposes exactly that, keeping each step at log k."),
            ("Sort all by distance", "Sort by x² + y² and take the first k.", "O(n log n)", "O(n)", "sort", S,
             "Correct, but it orders every point when only k are needed."),
            ("Pick the closest k times", "Scan for the nearest remaining point, k rounds.", "O(n·k)", "O(n)", "brute", S,
             "Correct, but each round rescans all points."),
            ("Smallest |x| + |y|", "Rank points by Manhattan distance.", "O(n log n)", "O(n)", "math", X,
             "(3,0) and (2,2): Manhattan says 3 < 4, Euclidean says 3 > 2.83. Different metric, different answer."),
        ],
    ),
    dict(
        slug="find-median-from-data-stream", n=295, title="Find Median from Data Stream", diff="Hard", topics=["data-structures"],
        summary="Design a structure that accepts numbers one at a time and can report the median of everything seen so far.",
        example="add 1, add 2 → median 1.5, add 3 → median 2",
        criterion="Which design has the best addNum / findMedian costs?",
        hint="The median splits the data into a lower half and an upper half.",
        choices=[
            ("Two heaps (max-heap low, min-heap high)", "Keep halves balanced; the median is at the tops.", "O(log n) add, O(1) median", "O(n)", "heap", O,
             "You only need the largest of the lower half and the smallest of the upper half. Two heaps expose exactly those two values."),
            ("Sorted array with insertion", "Binary search the position, insert, read the middle.", "O(n) add", "O(n)", "binary-search", S,
             "The search is log n, but inserting into an array shifts elements. What structure avoids the shift?"),
            ("Sort on every query", "Append on add; sort before reading the middle.", "O(n log n) median", "O(n)", "sort", S,
             "Correct, but frequent queries re-sort nearly identical data."),
            ("Running average", "Track sum and count; report sum / count.", "O(1)", "O(1)", "math", X,
             "Mean and median differ: for [1, 2, 100], the mean is 34.3, the median is 2."),
        ],
    ),
    # ---------------------------------------------------------------- Backtracking
    dict(
        slug="subsets", n=78, title="Subsets", diff="Medium", topics=["trees"],
        summary="Return every subset (the power set) of an array of distinct integers.",
        example="[1, 2, 3]  →  [[], [1], [2], [1,2], [3], [1,3], [2,3], [1,2,3]]",
        criterion="Which approach generates each subset exactly once?",
        hint="For each element, there are exactly two choices.",
        choices=[
            ("Backtracking: include / exclude", "Recurse over indices; branch on taking or skipping each element.", "O(n·2ⁿ)", "O(n)", "backtrack", O,
             "Each element is either in or out, so the choices form a binary tree with 2ⁿ leaves — one per subset, none repeated."),
            ("All permutations, dedupe as sets", "Generate every ordering of every length, then remove duplicates.", "O(n·n!)", "O(n·2ⁿ)", "brute", S,
             "It finds every subset, but orderings are irrelevant for subsets — n! explodes far past 2ⁿ."),
            ("All contiguous subarrays", "Take every nums[i..j].", "O(n³)", "O(n²)", "sliding-window", X,
             "Is [1, 3] a subarray of [1, 2, 3]? No, but it is a subset."),
            ("Empty set, singles and pairs", "Output subsets of size 0, 1 and 2.", "O(n²)", "O(n²)", "brute", X,
             "What about [1, 2, 3]? Subsets can be any size up to n."),
        ],
    ),
    dict(
        slug="combination-sum", n=39, title="Combination Sum", diff="Medium", topics=["trees"],
        summary="Given distinct positive candidates and a target, list every combination (numbers may repeat) that sums to the target.",
        example="candidates = [2,3,6,7], target = 7  →  [[2,2,3], [7]]",
        criterion="Which approach lists every combination without duplicates?",
        hint="How do you avoid generating [2,3,2] after [2,2,3]?",
        choices=[
            ("Backtracking with a start index", "Recurse from index i (reuse allowed), stop when the sum exceeds the target.", "O(n^(T/min))", "O(T/min)", "backtrack", O,
             "Only choosing candidates at or after the current index keeps each combination in non-decreasing order, so duplicates never appear. Overshooting prunes a branch."),
            ("Enumerate all sequences, then dedupe", "Generate every sequence up to length T/min, sort each, keep unique.", "O(n^(T/min)·T)", "O(n^(T/min))", "brute", S,
             "Correct, but orderings multiply the work and you still pay to dedupe. The start index prevents duplicates up front."),
            ("Greedy: largest candidate first", "Take the largest candidate that fits until you reach the target.", "O(T)", "O(1)", "greedy", X,
             "Greedy finds at most one combination and may miss the target: candidates [3,5], target 9 → 5 + 3 leaves 1, but 3+3+3 works."),
            ("Coin-change DP table", "dp[s] = number of ways to make s.", "O(n·T)", "O(T)", "dp-1d", X,
             "That counts combinations but doesn't list them. The problem asks for the actual lists."),
        ],
    ),
    dict(
        slug="word-search", n=79, title="Word Search", diff="Medium", topics=["trees", "grid"],
        summary="Decide whether a word can be traced through horizontally or vertically adjacent cells of a grid, using each cell at most once.",
        example='board 3×4, word = "ABCCED"  →  true',
        criterion="Which approach correctly respects the no-reuse rule efficiently?",
        hint="Mark a cell while it's on the current path, and unmark it when you back out.",
        choices=[
            ("DFS backtracking with visited marks", "From each matching cell, DFS to neighbors, marking/unmarking cells on the path.", "O(m·n·3^L)", "O(L)", "backtrack", O,
             "Each step has at most three new directions (you can't go back), and you stop as soon as a letter mismatches."),
            ("Enumerate all paths of length L", "Generate every path of length L from each cell, then compare to the word.", "O(m·n·4^L)", "O(L)", "brute", S,
             "Correct, but it explores paths that went wrong at the first letter. Comparing as you go prunes them."),
            ("BFS with a global visited set", "BFS from the start cell, never revisiting any cell.", "O(m·n)", "O(m·n)", "graph-bfs", X,
             "A cell used by one failed path might be needed by another. A global visited set blocks it forever."),
            ("Compare letter counts", "True if the grid has enough of each letter.", "O(m·n)", "O(Σ)", "counting", X,
             "Having the letters isn't the same as having them adjacent in the right order."),
        ],
    ),
    # ---------------------------------------------------------------- Graphs
    dict(
        slug="number-of-islands", n=200, title="Number of Islands", diff="Medium", topics=["grid"],
        summary="Count the connected groups of '1' cells (land) in a grid, connecting horizontally and vertically.",
        example='[["1","1","0"],["1","0","0"],["0","0","1"]]  →  2',
        criterion="Which approach is the standard linear answer?",
        hint="When you find unvisited land, how do you claim the whole island at once?",
        choices=[
            ("Flood fill (DFS/BFS) with marking", "On each unvisited '1', count an island and sink every connected land cell.", "O(m·n)", "O(m·n)", "graph-dfs", O,
             "Each island is one connected component. Flood filling marks it so it's counted once, and each cell is visited a constant number of times."),
            ("Count all '1' cells", "Return the number of land cells.", "O(m·n)", "O(1)", "counting", X,
             "An island of four cells counts as one island, not four."),
            ("Count top-left corners", "Count land cells whose up and left neighbors are water.", "O(m·n)", "O(1)", "matrix", X,
             "A U-shaped island has two such 'corners'. Local checks can't see how cells connect further away."),
            ("BFS per cell, no global marks", "From every land cell, BFS its island and dedupe islands by their cell sets.", "O((m·n)²)", "O(m·n)", "graph-bfs", S,
             "Correct in the end, but every cell re-explores its whole island. Marking once avoids the repetition."),
        ],
    ),
    dict(
        slug="course-schedule", n=207, title="Course Schedule", diff="Medium", topics=["graphs"],
        summary="Given course prerequisites as pairs, decide whether it is possible to finish every course.",
        example="n = 2, [[1,0],[0,1]]  →  false",
        criterion="Which approach is linear in courses + prerequisites?",
        hint="When is it impossible to take courses in some order?",
        choices=[
            ("Topological sort (Kahn's BFS)", "Repeatedly take courses with no remaining prerequisites; success if all are taken.", "O(V+E)", "O(V+E)", "topo", O,
             "A valid order exists exactly when the graph has no cycle. Kahn's algorithm peels off prerequisite-free courses and gets stuck only on a cycle."),
            ("Check only mutual pairs", "Fail if some a→b and b→a both exist.", "O(E)", "O(E)", "hashmap", X,
             "Cycles can be longer: 0→1→2→0 has no mutual pair."),
            ("DFS from every course without memo", "For each course, DFS to see if it can reach itself.", "O(V·(V+E))", "O(V)", "graph-dfs", S,
             "Correct, but the same subgraphs are re-explored from every start. Coloring nodes as done avoids that."),
            ("Take courses in numeric order", "Assume course numbers are a valid order.", "O(V)", "O(1)", "sort", X,
             "Nothing says lower-numbered courses come first. [[0,1]] means 1 must precede 0."),
        ],
    ),
    dict(
        slug="rotting-oranges", n=994, title="Rotting Oranges", diff="Medium", topics=["grid"],
        summary="Each minute, rotten oranges rot their fresh 4-directional neighbors. Return the minutes until no fresh orange remains, or −1 if impossible.",
        example="[[2,1,1],[1,1,0],[0,1,1]]  →  4",
        criterion="Which approach is linear in the grid size?",
        hint="All rotten oranges spread at the same time.",
        choices=[
            ("Multi-source BFS", "Enqueue every rotten orange at time 0, BFS level by level.", "O(m·n)", "O(m·n)", "graph-bfs", O,
             "Starting BFS from all sources together simulates simultaneous spreading. Each level is one minute and each cell is processed once."),
            ("Simulate minute by minute", "Each minute, scan the grid and rot neighbors of rotten cells.", "O((m·n)²)", "O(m·n)", "matrix", S,
             "Correct, but each minute rescans cells that can't change. A queue only touches the frontier."),
            ("Deepest DFS from each rotten orange", "Run DFS from each rotten cell; report the largest recursion depth.", "O(m·n)", "O(m·n)", "graph-dfs", X,
             "DFS depth isn't shortest distance — it can snake along long paths. Rot spreads by shortest paths."),
            ("Count the fresh oranges", "Return the number of fresh oranges.", "O(m·n)", "O(1)", "counting", X,
             "Many oranges can rot in the same minute. The answer is a time, not a count."),
        ],
    ),
    dict(
        slug="clone-graph", n=133, title="Clone Graph", diff="Medium", topics=["graphs"],
        summary="Return a deep copy of a connected undirected graph given one of its nodes.",
        example="adjacency [[2,4],[1,3],[2,4],[1,3]]  →  identical structure, new nodes",
        criterion="Which approach is linear and handles cycles?",
        hint="How do you avoid cloning the same node twice?",
        choices=[
            ("DFS/BFS with old → new map", "Clone each node once; look up clones in a map when wiring neighbors.", "O(V+E)", "O(V)", "graph-dfs", O,
             "The map says whether a node was already copied, which both stops infinite loops on cycles and makes shared neighbors point to one clone."),
            ("Copy nodes, keep neighbor references", "Create new nodes but reuse the original neighbor lists.", "O(V)", "O(V)", "array-copy", X,
             "The copies would point at original nodes — that's a shallow copy, not a deep one."),
            ("Recursive clone without memo", "clone(node) creates a node and clones each neighbor.", "∞ on cycles", "—", "recursion", X,
             "In an undirected graph, 1 → 2 → 1 → 2 … Without remembering visited nodes, does recursion ever stop?"),
            ("Serialize, then rebuild by searching", "Write an adjacency list, create nodes, then find each neighbor by scanning the node list.", "O(V·E)", "O(V+E)", "brute", S,
             "Correct, but each neighbor lookup is a linear search. A map makes it O(1)."),
        ],
    ),
    # ---------------------------------------------------------------- Advanced Graphs
    dict(
        slug="network-delay-time", n=743, title="Network Delay Time", diff="Medium", topics=["graphs", "data-structures"],
        summary="A signal starts at node k in a directed graph with positive edge travel times. Return the time for all nodes to receive it, or −1.",
        example="times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2  →  2",
        criterion="Which approach is best for positive weights?",
        hint="You need the shortest weighted distance to every node; the answer is the largest of them.",
        choices=[
            ("Dijkstra with a min-heap", "Pop the closest unsettled node, relax its edges.", "O(E log V)", "O(V+E)", "dijkstra", O,
             "With positive weights, the closest unsettled node's distance is final. The heap always hands you that node next."),
            ("Bellman–Ford", "Relax every edge V−1 times.", "O(V·E)", "O(V)", "graph-bfs", S,
             "Correct (and handles negative edges), but with positive weights that generality costs a factor of V."),
            ("Plain BFS counting hops", "BFS from k; the time is the number of levels.", "O(V+E)", "O(V)", "graph-bfs", X,
             "Edges have different travel times. A two-hop path can be faster than a one-hop path."),
            ("Floyd–Warshall", "All-pairs shortest paths, then read row k.", "O(V³)", "O(V²)", "dp-2d", S,
             "Correct, but it computes distances from every source. You only need one."),
        ],
    ),
    dict(
        slug="min-cost-to-connect-all-points", n=1584, title="Min Cost to Connect All Points", diff="Medium", topics=["graphs"],
        summary="Connect all 2-D points so any two are linked by some path, minimizing total Manhattan edge length.",
        example="[[0,0],[2,2],[3,10],[5,2],[7,0]]  →  20",
        criterion="Which approach is the standard answer?",
        hint="You need a minimum spanning tree over a complete graph.",
        choices=[
            ("Prim's algorithm with a min-heap", "Grow a tree from one point; always add the cheapest edge to a new point.", "O(n² log n)", "O(n²)", "dijkstra", O,
             "The cheapest edge leaving the current tree is always safe to add (cut property). A heap finds it quickly."),
            ("Connect each point to its nearest", "Add an edge from every point to its closest neighbor.", "O(n²)", "O(n)", "greedy", X,
             "Two tight clusters far apart would each link internally and never connect to each other."),
            ("Dijkstra tree from point 0", "Use shortest paths from point 0 as the network.", "O(n² log n)", "O(n²)", "dijkstra", X,
             "Shortest-path trees minimize distance from one source, not total edge length. They can cost more than the MST."),
            ("Try all spanning trees", "Enumerate spanning trees and keep the cheapest.", "O(n^(n−2))", "O(n)", "brute", S,
             "Cayley's formula says there are n^(n−2) of them. Correct, but only for tiny n."),
        ],
    ),
    # ---------------------------------------------------------------- Intervals
    dict(
        slug="merge-intervals", n=56, title="Merge Intervals", diff="Medium", topics=["greedy"],
        summary="Merge all overlapping intervals and return the non-overlapping result.",
        example="[[1,3],[2,6],[8,10],[15,18]]  →  [[1,6],[8,10],[15,18]]",
        criterion="Which approach is the standard answer?",
        hint="After a certain sort, which interval can the next one possibly overlap?",
        choices=[
            ("Sort by start, merge in one pass", "Extend the last merged interval if the next starts within it; otherwise append.", "O(n log n)", "O(n)", "intervals", O,
             "Sorted by start, an interval can only overlap the most recent merged block. One comparison per interval does the rest."),
            ("Merge any overlapping pair repeatedly", "Scan pairs, merge overlaps, repeat until nothing changes.", "O(n³)", "O(n)", "brute", S,
             "Correct in the end, but each pass checks all pairs and many passes may be needed."),
            ("Mark integers on a number line", "Mark every covered integer, then read runs.", "O(n + range)", "O(range)", "array-copy", X,
             "[1,2] and [3,4] don't overlap, but marking integers makes 1–4 look like one run."),
            ("Sort by end, merge with the last", "Sort by end point, then merge adjacent overlaps.", "O(n log n)", "O(n)", "sort", X,
             "Try [[2,3],[4,5],[1,10]]: sorted by end, [1,10] only meets [4,5] and leaves [2,3] unmerged."),
        ],
    ),
    dict(
        slug="meeting-rooms-ii", n=253, title="Meeting Rooms II", diff="Medium", topics=["data-structures", "greedy"],
        summary="Given meeting time intervals, return the minimum number of rooms needed so no meetings overlap in the same room.",
        example="[[0,30],[5,10],[15,20]]  →  2",
        criterion="Which approach is the standard answer?",
        hint="When a meeting starts, which ongoing meeting will free its room first?",
        choices=[
            ("Sort by start + min-heap of end times", "For each meeting, free the earliest-ending room if it's done, then push this end time.", "O(n log n)", "O(n)", "heap", O,
             "The heap's top is the room that frees up soonest. If it's not free yet, no room is, so you need a new one. The heap size is the answer."),
            ("Max pairwise-overlap count", "For each meeting, count meetings overlapping it; return the max + 1.", "O(n²)", "O(1)", "brute", X,
             "[0,5], [4,7], [6,10]: the middle meeting overlaps two others, so this answers 3 — but the outer two never overlap, so 2 rooms suffice."),
            ("Timeline counter per minute", "Increment every minute a meeting covers; return the max.", "O(n·T)", "O(T)", "array-copy", S,
             "Correct, but the cost depends on the time range T, which can be huge. Only start and end events matter."),
            ("Assign to first free room by scan", "Sort by start; scan rooms for one whose last meeting ended.", "O(n·r)", "O(r)", "greedy", S,
             "Correct, but scanning rooms is linear. A heap finds the earliest-free room in log time."),
        ],
    ),
    dict(
        slug="non-overlapping-intervals", n=435, title="Non-overlapping Intervals", diff="Medium", topics=["greedy"],
        summary="Return the minimum number of intervals to remove so the rest do not overlap.",
        example="[[1,2],[2,3],[3,4],[1,3]]  →  1",
        criterion="Which approach is best for n up to 10⁵?",
        hint="To fit as many intervals as possible, which one should you keep first?",
        choices=[
            ("Sort by end, keep earliest finishers", "Keep an interval if it starts after the last kept end; count the rest.", "O(n log n)", "O(1)", "greedy", O,
             "Finishing earliest leaves the most room for everything after. Keeping the maximum set means removing the minimum."),
            ("Sort by start, keep the first", "Keep each interval that starts after the last kept one; skip others.", "O(n log n)", "O(1)", "sort", X,
             "[[1,100],[2,3],[4,5]] keeps [1,100] and removes two, but removing just [1,100] is enough."),
            ("DP over sorted intervals (LIS-style)", "dp[i] = most compatible intervals ending with i.", "O(n²)", "O(n)", "dp-1d", S,
             "Correct, but quadratic. The greedy exchange argument shows DP isn't needed."),
            ("Remove the longest repeatedly", "While overlaps exist, remove the longest interval.", "O(n²)", "O(n)", "brute", X,
             "Length isn't what causes conflicts. A short interval can overlap many others."),
        ],
    ),
    # ---------------------------------------------------------------- Greedy
    dict(
        slug="maximum-subarray", n=53, title="Maximum Subarray", diff="Medium", topics=["dp", "data-structures"],
        summary="Find the largest sum of any non-empty contiguous subarray.",
        example="[-2,1,-3,4,-1,2,1,-5,4]  →  6  ([4,-1,2,1])",
        criterion="Which approach is best for n up to 10⁵?",
        hint="When is a running prefix no longer worth keeping?",
        choices=[
            ("Kadane's algorithm", "cur = max(x, cur + x); track the best cur.", "O(n)", "O(1)", "greedy", O,
             "If the running sum drops below zero, would any future subarray want to include it? No — so restart. That's one pass."),
            ("All subarrays with running sums", "For each start, extend and track the best sum.", "O(n²)", "O(1)", "brute", S,
             "Correct, but many starts are never worth considering. Which ones can you discard?"),
            ("Divide and conquer", "Best of left half, right half, or crossing the middle.", "O(n log n)", "O(log n)", "recursion", S,
             "Correct and a classic, but it does log n levels of work that one linear pass avoids."),
            ("Sum all positive numbers", "Add every positive value.", "O(n)", "O(1)", "math", X,
             "The subarray must be contiguous. You can't skip the negative numbers in between."),
        ],
    ),
    dict(
        slug="jump-game", n=55, title="Jump Game", diff="Medium", topics=["greedy"],
        summary="Each value is the maximum jump length from that index. Decide whether you can reach the last index from the first.",
        example="[2,3,1,1,4] → true,  [3,2,1,0,4] → false",
        criterion="Which approach is best for n up to 10⁴?",
        hint="Instead of choosing jumps, track how far you could possibly reach.",
        choices=[
            ("Greedy farthest reach", "Scan; if i > reach fail, else reach = max(reach, i + nums[i]).", "O(n)", "O(1)", "greedy", O,
             "Every index up to reach is reachable, so you only need the maximum reach so far. One pass decides it."),
            ("DP reachable array", "Mark each index reachable from any earlier reachable index.", "O(n²)", "O(n)", "dp-1d", S,
             "Correct, but it checks every earlier index. The reachable set is always a prefix — one number describes it."),
            ("Always take the maximum jump", "From each index, jump as far as possible.", "O(n)", "O(1)", "greedy", X,
             "[2,3,0,1,4]: the max jump from index 0 lands on the 0 and gets stuck, while a 1-step jump reaches the 3 and then the end."),
            ("Fail if the array contains a 0", "Any zero before the end blocks progress.", "O(n)", "O(1)", "counting", X,
             "In [2,0,0], you can jump over the first 0 straight to the end."),
        ],
    ),
    # ---------------------------------------------------------------- 1-D DP
    dict(
        slug="climbing-stairs", n=70, title="Climbing Stairs", diff="Easy", topics=["dp"],
        summary="You climb 1 or 2 steps at a time. Count the distinct ways to reach step n.",
        example="n = 3  →  3  (1+1+1, 1+2, 2+1)",
        criterion="Which approach is linear with O(1) space?",
        hint="How can you arrive at step n?",
        choices=[
            ("Bottom-up DP with two variables", "ways(n) = ways(n−1) + ways(n−2), keep only the last two.", "O(n)", "O(1)", "dp-1d", O,
             "Your last move was a 1-step or a 2-step, so ways(n) is the sum of the two previous counts. You only ever need two numbers."),
            ("Plain recursion", "Return f(n−1) + f(n−2) directly.", "O(2ⁿ)", "O(n)", "recursion", S,
             "Correct, but f(n−2) is computed again inside f(n−1). The call tree explodes."),
            ("Memoized recursion", "Cache f(k) as you recurse.", "O(n)", "O(n)", "recursion", S,
             "Linear time, but it keeps a cache and a call stack of size n. Do you need more than the last two values?"),
            ("n / 2 + 1", "Count how many 2-steps you could take.", "O(1)", "O(1)", "math", X,
             "That counts step mixes, not orderings: 1+2 and 2+1 are different ways."),
        ],
    ),
    dict(
        slug="house-robber", n=198, title="House Robber", diff="Medium", topics=["dp"],
        summary="Pick houses to rob for maximum money without ever robbing two adjacent houses.",
        example="[2, 7, 9, 3, 1]  →  12  (2 + 9 + 1)",
        criterion="Which approach is linear with O(1) space?",
        hint="At house i, you either rob it or you don't.",
        choices=[
            ("DP rob/skip with two variables", "best(i) = max(best(i−1), best(i−2) + money[i]).", "O(n)", "O(1)", "dp-1d", O,
             "Robbing i means you skipped i−1; skipping i means you keep best(i−1). Two running values capture both."),
            ("Max of even vs. odd indices", "Sum even-indexed houses and odd-indexed houses; take the larger.", "O(n)", "O(1)", "math", X,
             "[2,1,1,2]: evens = 3, odds = 3, but robbing houses 0 and 3 gives 4."),
            ("Try all non-adjacent subsets", "Enumerate every valid selection.", "O(2ⁿ)", "O(n)", "backtrack", S,
             "Correct but exponential; the choices at i only depend on the best answers up to i−1 and i−2."),
            ("Greedy: take the richest house first", "Repeatedly rob the largest remaining house and block its neighbors.", "O(n log n)", "O(n)", "greedy", X,
             "[3,4,3]: greedy takes 4, but 3 + 3 = 6 is better."),
        ],
    ),
    dict(
        slug="coin-change", n=322, title="Coin Change", diff="Medium", topics=["dp"],
        summary="Given coin denominations (unlimited supply) and an amount, return the fewest coins that sum to the amount, or −1.",
        example="coins = [1, 2, 5], amount = 11  →  3  (5 + 5 + 1)",
        criterion="Which approach is correct for arbitrary denominations?",
        hint="The best way to make amount a uses the best way to make a − c for some coin c.",
        choices=[
            ("Bottom-up DP over amounts", "dp[a] = 1 + min(dp[a − c]) over coins c.", "O(amount·coins)", "O(amount)", "dp-1d", O,
             "The last coin used is some c, and what remains must be made optimally. Filling amounts from 0 upward ensures every subproblem is ready."),
            ("Greedy: largest coin first", "Take as many of the largest coin as fit, then the next.", "O(coins)", "O(1)", "greedy", X,
             "coins = [1,3,4], amount = 6: greedy gives 4+1+1 (3 coins), but 3+3 needs 2."),
            ("Plain recursion over coins", "Try every coin at every step, no caching.", "O(coins^amount)", "O(amount)", "recursion", S,
             "Correct, but the same remaining amounts are solved again and again. Caching turns this into DP."),
            ("DP using only the largest fitting coin", "dp[a] = 1 + dp[a − largest coin ≤ a].", "O(amount)", "O(amount)", "dp-1d", X,
             "That's the greedy choice dressed up as DP. It fails on the same [1,3,4], 6 example."),
        ],
    ),
    dict(
        slug="word-break", n=139, title="Word Break", diff="Medium", topics=["dp"],
        summary="Decide whether a string can be split into a sequence of dictionary words (words may be reused).",
        example='s = "leetcode", dict = ["leet", "code"]  →  true',
        criterion="Which approach is polynomial and correct?",
        hint="If the prefix s[0:i] can be split, what else do you need?",
        choices=[
            ("DP over prefixes", "dp[i] = true if some word w ends at i and dp[i − |w|] is true.", "O(n·W·L)", "O(n)", "dp-1d", O,
             "A split of s[0:i] ends with some word. If the part before it is splittable, so is s[0:i]. Each prefix is solved once."),
            ("Greedy longest match", "Repeatedly strip the longest dictionary word from the front.", "O(n·W·L)", "O(1)", "greedy", X,
             "s = \"aaaaaa\", dict = [\"aaaa\", \"aaa\"]: greedy takes \"aaaa\" and is left with \"aa\", yet \"aaa\" + \"aaa\" works."),
            ("Recursion without memoization", "Try each word at the front and recurse on the rest.", "O(2ⁿ)", "O(n)", "recursion", S,
             "Correct, but the same suffix is re-solved many times. Memoizing each start index gives the DP."),
            ("Every character appears in some word", "Check each letter occurs in the dictionary.", "O(n + W·L)", "O(Σ)", "counting", X,
             "\"ab\" with dictionary [\"a\", \"bc\"] passes this check, but 'b' alone is not a word."),
        ],
    ),
    dict(
        slug="longest-increasing-subsequence", n=300, title="Longest Increasing Subsequence", diff="Medium", topics=["dp", "binary-search"],
        summary="Return the length of the longest strictly increasing subsequence (not necessarily contiguous).",
        example="[10, 9, 2, 5, 3, 7, 101, 18]  →  4  (2, 3, 7, 101)",
        criterion="The follow-up asks for better than O(n²). Which approach achieves it?",
        hint="For each length, keep the smallest possible tail value.",
        choices=[
            ("Tails array + binary search", "tails[k] = smallest tail of an increasing run of length k+1; binary search to place each x.", "O(n log n)", "O(n)", "binary-search", O,
             "A smaller tail can only help future extensions. tails stays sorted, so each value finds its slot by binary search."),
            ("O(n²) DP", "dp[i] = 1 + max(dp[j]) for j < i with nums[j] < nums[i].", "O(n²)", "O(n)", "dp-1d", S,
             "Correct and very common, but it doesn't meet the follow-up. Which information about earlier runs actually matters?"),
            ("Longest increasing contiguous run", "Scan for the longest stretch where each value increases.", "O(n)", "O(1)", "sliding-window", X,
             "A subsequence can skip elements: 2, 3, 7, 101 aren't adjacent in the input."),
            ("Check every subsequence", "Enumerate all 2ⁿ subsequences.", "O(n·2ⁿ)", "O(n)", "brute", S,
             "Correct but exponential."),
        ],
    ),
    # ---------------------------------------------------------------- 2-D DP
    dict(
        slug="unique-paths", n=62, title="Unique Paths", diff="Medium", topics=["dp"],
        summary="A robot moves only right or down on an m × n grid. Count the paths from the top-left to the bottom-right corner.",
        example="m = 3, n = 7  →  28",
        criterion="Which approach is the standard DP answer?",
        hint="How many ways are there to arrive at a cell?",
        choices=[
            ("Grid DP (rolling row)", "paths[r][c] = paths[r−1][c] + paths[r][c−1], keep one row.", "O(m·n)", "O(n)", "dp-2d", O,
             "You enter a cell from above or from the left, so its count is the sum of theirs. Each row only needs the previous row."),
            ("Plain recursion", "f(r, c) = f(r−1, c) + f(r, c−1) without caching.", "O(2^(m+n))", "O(m+n)", "recursion", S,
             "Correct, but the same cells are recomputed exponentially many times."),
            ("m × n", "Multiply the dimensions.", "O(1)", "O(1)", "math", X,
             "m·n counts cells, not paths. For a 3×7 grid, that's 21, but there are 28 paths."),
            ("Only the two border paths", "Always 2: all right then down, or all down then right.", "O(1)", "O(1)", "math", X,
             "Paths can zig-zag: right, down, right, down … each is distinct."),
        ],
    ),
    dict(
        slug="longest-common-subsequence", n=1143, title="Longest Common Subsequence", diff="Medium", topics=["dp"],
        summary="Return the length of the longest subsequence common to two strings.",
        example='"abcde", "ace"  →  3  ("ace")',
        criterion="Which approach is the standard polynomial answer?",
        hint="Compare the last characters of the two prefixes.",
        choices=[
            ("2-D DP over prefixes", "dp[i][j] = dp[i−1][j−1] + 1 if chars match, else max(dp[i−1][j], dp[i][j−1]).", "O(m·n)", "O(m·n)", "dp-2d", O,
             "If the last characters match, they extend the LCS of the shorter prefixes; if not, one of them is dropped. Every prefix pair is solved once."),
            ("Check every subsequence of one string", "Enumerate subsequences of s1 and test each against s2.", "O(2^m·n)", "O(m)", "brute", S,
             "Correct but exponential in m."),
            ("Greedy first matches", "Walk s1; for each char, match its next occurrence in s2.", "O(m·n)", "O(1)", "greedy", X,
             "s1 = 'zabc', s2 = 'abcz': greedy matches 'z' to the end of s2 and finds nothing after it (1), but 'abc' gives 3."),
            ("Longest common substring DP", "dp[i][j] = dp[i−1][j−1] + 1 on match, else 0.", "O(m·n)", "O(m·n)", "dp-2d", X,
             "Resetting to 0 forces contiguity. A subsequence may skip characters."),
        ],
    ),
    # ---------------------------------------------------------------- Bit Manipulation
    dict(
        slug="single-number", n=136, title="Single Number", diff="Easy", topics=["bit-manipulation"],
        summary="Every value appears twice except one. Find the one that appears once.",
        example="[4, 1, 2, 1, 2]  →  4",
        criterion="Which approach is linear time with O(1) extra space?",
        hint="Which operation cancels a value with itself?",
        choices=[
            ("XOR everything", "Fold the array with ^.", "O(n)", "O(1)", "bits", O,
             "x ^ x = 0 and x ^ 0 = x, and XOR is order-independent. Every pair cancels, leaving the single value."),
            ("Hash map counts", "Count occurrences; return the value with count 1.", "O(n)", "O(n)", "hashmap", S,
             "Correct, but it needs O(n) memory. Is there an operation where pairs cancel on their own?"),
            ("2·sum(set) − sum(array)", "Use distinct values to cancel duplicates arithmetically.", "O(n)", "O(n)", "math", S,
             "Clever and correct, but the set costs O(n) space."),
            ("AND everything", "Fold the array with &.", "O(n)", "O(1)", "bits", X,
             "AND doesn't cancel duplicates: 4 & 1 & 2 & 1 & 2 = 0."),
        ],
    ),
    dict(
        slug="counting-bits", n=338, title="Counting Bits", diff="Easy", topics=["bit-manipulation", "dp"],
        summary="For every i from 0 to n, return the number of 1 bits in i.",
        example="n = 5  →  [0, 1, 1, 2, 1, 2]",
        criterion="The follow-up asks for a single O(n) pass. Which approach meets it?",
        hint="How does i relate to i >> 1?",
        choices=[
            ("DP: bits[i] = bits[i >> 1] + (i & 1)", "Reuse the count of i with its last bit dropped.", "O(n)", "O(n)", "bits", O,
             "Shifting right drops exactly the last bit. So i's count is its half's count plus that last bit — already computed."),
            ("Count bits of each number", "Loop over each bit of every i.", "O(n log n)", "O(n)", "brute", S,
             "Correct, but it recounts bits that smaller numbers already counted."),
            ("bits[i] = bits[i − 1] + 1", "Assume each increment adds one bit.", "O(n)", "O(n)", "dp-1d", X,
             "3 → 4 is 011 → 100: the count drops from 2 to 1. Carries clear bits."),
            ("⌊log₂ i⌋ + 1", "Use the bit length.", "O(n)", "O(n)", "math", X,
             "That's how many bits i has, not how many are 1. 4 = 100 has length 3 but one 1."),
        ],
    ),
    # ---------------------------------------------------------------- Math & Geometry
    dict(
        slug="rotate-image", n=48, title="Rotate Image", diff="Medium", topics=["math"],
        summary="Rotate an n × n matrix 90° clockwise in place.",
        example="[[1,2,3],[4,5,6],[7,8,9]]  →  [[7,4,1],[8,5,2],[9,6,3]]",
        criterion="The rotation must happen in place.",
        hint="Rotation can be decomposed into two simple reflections.",
        choices=[
            ("Transpose, then reverse each row", "Swap across the diagonal, then reverse rows.", "O(n²)", "O(1)", "matrix", O,
             "A transpose flips across the diagonal; reversing rows flips left–right. Together they make a clockwise rotation without extra memory."),
            ("Copy into a new matrix", "result[c][n−1−r] = m[r][c], then copy back.", "O(n²)", "O(n²)", "array-copy", S,
             "Correct, but it uses a full second matrix, which the in-place requirement forbids."),
            ("Reverse the rows only", "Reverse each row.", "O(n²)", "O(1)", "matrix", X,
             "That's a horizontal mirror, not a rotation. The first row stays on top."),
            ("Transpose only", "Swap across the diagonal.", "O(n²)", "O(1)", "matrix", X,
             "A transpose is a reflection. 1 stays in the top-left corner, but a rotation moves it to the top-right."),
        ],
    ),
    dict(
        slug="powx-n", n=50, title="Pow(x, n)", diff="Medium", topics=["math", "bit-manipulation"],
        summary="Compute x raised to an integer power n, where n may be negative and as large as 2³¹ − 1 in magnitude.",
        example="x = 2.0, n = -2  →  0.25",
        criterion="Which approach handles |n| up to 2³¹?",
        hint="x⁸ = ((x²)²)².",
        choices=[
            ("Exponentiation by squaring", "Square x and halve n; multiply the result when n's low bit is 1. Invert for negative n.", "O(log n)", "O(1)", "bits", O,
             "Each squaring doubles the exponent covered, so about 31 steps reach 2³¹. Handling the sign by inverting x keeps it general."),
            ("Multiply n times", "Loop |n| times.", "O(n)", "O(1)", "brute", S,
             "Correct, but 2³¹ multiplications is far too slow."),
            ("Ignore the sign of n", "Compute x^|n|.", "O(log n)", "O(1)", "bits", X,
             "x^(−2) = 1/x². Dropping the sign returns x² instead."),
            ("exp(n · ln x)", "Use logarithms.", "O(1)", "O(1)", "math", X,
             "ln x is undefined for negative x, so (−2)³ breaks; it also loses precision."),
        ],
    ),
]
